//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cryptopia.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Authorization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Authorization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cryptopia.Resources.Authorization", typeof(Authorization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer 1.
        /// </summary>
        public static string twoFactorAnswer1Label {
            get {
                return ResourceManager.GetString("twoFactorAnswer1Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer 2.
        /// </summary>
        public static string twoFactorAnswer2Label {
            get {
                return ResourceManager.GetString("twoFactorAnswer2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A..
        /// </summary>
        public static string twoFactorAnswerShortLabel {
            get {
                return ResourceManager.GetString("twoFactorAnswerShortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lockout.
        /// </summary>
        public static string twoFactorComponent_Lockout {
            get {
                return ResourceManager.GetString("twoFactorComponent_Lockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string twoFactorComponent_Login {
            get {
                return ResourceManager.GetString("twoFactorComponent_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string twoFactorComponent_Settings {
            get {
                return ResourceManager.GetString("twoFactorComponent_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip.
        /// </summary>
        public static string twoFactorComponent_Tip {
            get {
                return ResourceManager.GetString("twoFactorComponent_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string twoFactorComponent_Transfer {
            get {
                return ResourceManager.GetString("twoFactorComponent_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw.
        /// </summary>
        public static string twoFactorComponent_Withdraw {
            get {
                return ResourceManager.GetString("twoFactorComponent_Withdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string twoFactorCryptopiaCodeLabel {
            get {
                return ResourceManager.GetString("twoFactorCryptopiaCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your Cryptopia Authenticator code..
        /// </summary>
        public static string twoFactorCryptopiaSummary {
            get {
                return ResourceManager.GetString("twoFactorCryptopiaSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string twoFactorDataAnswer1Label {
            get {
                return ResourceManager.GetString("twoFactorDataAnswer1Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string twoFactorDataAnswer2Label {
            get {
                return ResourceManager.GetString("twoFactorDataAnswer2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string twoFactorDataEmailLabel {
            get {
                return ResourceManager.GetString("twoFactorDataEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Code.
        /// </summary>
        public static string twoFactorDataPinLabel {
            get {
                return ResourceManager.GetString("twoFactorDataPinLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PinCode must be between 4 and 8 digits.
        /// </summary>
        public static string twoFactorDataPinPatternError {
            get {
                return ResourceManager.GetString("twoFactorDataPinPatternError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string twoFactorDataQuestion1Label {
            get {
                return ResourceManager.GetString("twoFactorDataQuestion1Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string twoFactorDataQuestion2Label {
            get {
                return ResourceManager.GetString("twoFactorDataQuestion2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string twoFactorEmailCodeLabel {
            get {
                return ResourceManager.GetString("twoFactorEmailCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter email code..
        /// </summary>
        public static string twoFactorEmailSummary {
            get {
                return ResourceManager.GetString("twoFactorEmailSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string twoFactorGoogleCodeLabel {
            get {
                return ResourceManager.GetString("twoFactorGoogleCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Google Authenticator code..
        /// </summary>
        public static string twoFactorGoogleSummary {
            get {
                return ResourceManager.GetString("twoFactorGoogleSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string twoFactorPasswordLabel {
            get {
                return ResourceManager.GetString("twoFactorPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter password..
        /// </summary>
        public static string twoFactorPasswordSummary {
            get {
                return ResourceManager.GetString("twoFactorPasswordSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin.
        /// </summary>
        public static string twoFactorPinLabel {
            get {
                return ResourceManager.GetString("twoFactorPinLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter pin code..
        /// </summary>
        public static string twoFactorPinSummary {
            get {
                return ResourceManager.GetString("twoFactorPinSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Question 1.
        /// </summary>
        public static string twoFactorQuestion1Label {
            get {
                return ResourceManager.GetString("twoFactorQuestion1Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Question 2.
        /// </summary>
        public static string twoFactorQuestion2Label {
            get {
                return ResourceManager.GetString("twoFactorQuestion2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q..
        /// </summary>
        public static string twoFactorQuestionShortLabel {
            get {
                return ResourceManager.GetString("twoFactorQuestionShortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please answer the security questions..
        /// </summary>
        public static string twoFactorQuestionSummary {
            get {
                return ResourceManager.GetString("twoFactorQuestionSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cryptopia Device.
        /// </summary>
        public static string twoFactorType_Cryptopia {
            get {
                return ResourceManager.GetString("twoFactorType_Cryptopia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string twoFactorType_Email {
            get {
                return ResourceManager.GetString("twoFactorType_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Authenticator.
        /// </summary>
        public static string twoFactorType_Google {
            get {
                return ResourceManager.GetString("twoFactorType_Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string twoFactorType_Password {
            get {
                return ResourceManager.GetString("twoFactorType_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Number.
        /// </summary>
        public static string twoFactorType_Pin {
            get {
                return ResourceManager.GetString("twoFactorType_Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Questions.
        /// </summary>
        public static string twoFactorType_Questions {
            get {
                return ResourceManager.GetString("twoFactorType_Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string twoFactorTypeLabel {
            get {
                return ResourceManager.GetString("twoFactorTypeLabel", resourceCulture);
            }
        }
    }
}
