//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cryptopia.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Paytopia {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Paytopia() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cryptopia.Resources.Paytopia", typeof(Paytopia).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithm.
        /// </summary>
        public static string exchangeAlgorithmLabel {
            get {
                return ResourceManager.GetString("exchangeAlgorithmLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block Explorer Link.
        /// </summary>
        public static string exchangeBlockExplorerLinkLabel {
            get {
                return ResourceManager.GetString("exchangeBlockExplorerLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Website.
        /// </summary>
        public static string exchangeCurrencyWebsiteLabel {
            get {
                return ResourceManager.GetString("exchangeCurrencyWebsiteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Information.
        /// </summary>
        public static string exchangeExtraInformationLabel {
            get {
                return ResourceManager.GetString("exchangeExtraInformationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Forum Thread.
        /// </summary>
        public static string exchangeLaunchForumThreadLabel {
            get {
                return ResourceManager.GetString("exchangeLaunchForumThreadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string exchangeNameLabel {
            get {
                return ResourceManager.GetString("exchangeNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Type.
        /// </summary>
        public static string exchangeNetworkTypeLabel {
            get {
                return ResourceManager.GetString("exchangeNetworkTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Code link.
        /// </summary>
        public static string exchangeSourceCodeLinkLabel {
            get {
                return ResourceManager.GetString("exchangeSourceCodeLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticker.
        /// </summary>
        public static string exchangeTickerLabel {
            get {
                return ResourceManager.GetString("exchangeTickerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string lottoCurrencyLabel {
            get {
                return ResourceManager.GetString("lottoCurrencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Description.
        /// </summary>
        public static string lottoDescriptionLabel {
            get {
                return ResourceManager.GetString("lottoDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Title.
        /// </summary>
        public static string lottoGameTitleLabel {
            get {
                return ResourceManager.GetString("lottoGameTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Price.
        /// </summary>
        public static string lottoTicketPriceLabel {
            get {
                return ResourceManager.GetString("lottoTicketPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithm.
        /// </summary>
        public static string poolListingAlgorithmLabel {
            get {
                return ResourceManager.GetString("poolListingAlgorithmLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block Explorer Link.
        /// </summary>
        public static string poolListingExplorerLabel {
            get {
                return ResourceManager.GetString("poolListingExplorerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Information.
        /// </summary>
        public static string poolListingExtraLabel {
            get {
                return ResourceManager.GetString("poolListingExtraLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Forum Thread.
        /// </summary>
        public static string poolListingForumLabel {
            get {
                return ResourceManager.GetString("poolListingForumLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Pool Already Listed.
        /// </summary>
        public static string poolListingIsListedLabel {
            get {
                return ResourceManager.GetString("poolListingIsListedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string poolListingNameLabel {
            get {
                return ResourceManager.GetString("poolListingNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Type.
        /// </summary>
        public static string poolListingNetworkTypeLabel {
            get {
                return ResourceManager.GetString("poolListingNetworkTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool.
        /// </summary>
        public static string poolListingPoolLabel {
            get {
                return ResourceManager.GetString("poolListingPoolLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Code Link.
        /// </summary>
        public static string poolListingSourceLabel {
            get {
                return ResourceManager.GetString("poolListingSourceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticker.
        /// </summary>
        public static string poolListingSymbolLabel {
            get {
                return ResourceManager.GetString("poolListingSymbolLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Link.
        /// </summary>
        public static string poolListingWebsiteLabel {
            get {
                return ResourceManager.GetString("poolListingWebsiteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City/State.
        /// </summary>
        public static string sharesCityStateLabel {
            get {
                return ResourceManager.GetString("sharesCityStateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shares to purchase.
        /// </summary>
        public static string sharesCountLabel {
            get {
                return ResourceManager.GetString("sharesCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string sharesCountryLabel {
            get {
                return ResourceManager.GetString("sharesCountryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emails Address.
        /// </summary>
        public static string sharesEmailsAddressLabel {
            get {
                return ResourceManager.GetString("sharesEmailsAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string sharesFirstNameLabel {
            get {
                return ResourceManager.GetString("sharesFirstNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string sharesLastNameLabel {
            get {
                return ResourceManager.GetString("sharesLastNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle name(s).
        /// </summary>
        public static string sharesMiddleNameLabel {
            get {
                return ResourceManager.GetString("sharesMiddleNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number (Country) (Area) (Number).
        /// </summary>
        public static string sharesPhoneLabel {
            get {
                return ResourceManager.GetString("sharesPhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post code.
        /// </summary>
        public static string sharesPostCodeLabel {
            get {
                return ResourceManager.GetString("sharesPostCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Address.
        /// </summary>
        public static string sharesStreetAddressLabel {
            get {
                return ResourceManager.GetString("sharesStreetAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City/State.
        /// </summary>
        public static string twoFactorCityStateLabel {
            get {
                return ResourceManager.GetString("twoFactorCityStateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string twoFactorCountryLabel {
            get {
                return ResourceManager.GetString("twoFactorCountryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post code.
        /// </summary>
        public static string twoFactorPostCodeLabel {
            get {
                return ResourceManager.GetString("twoFactorPostCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient.
        /// </summary>
        public static string twoFactorRecipientLabel {
            get {
                return ResourceManager.GetString("twoFactorRecipientLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Address.
        /// </summary>
        public static string twoFactorStreetAddressLabel {
            get {
                return ResourceManager.GetString("twoFactorStreetAddressLabel", resourceCulture);
            }
        }
    }
}
