CREATE TABLE [dbo].[MarketItem]
(
	[Id] INT IDENTITY (1, 1) NOT NULL, 
    [UserId] UNIQUEIDENTIFIER NOT NULL, 
	[CategoryId] INT NOT NULL, 
	[CurrencyId] INT NOT NULL,
	[MarketItemTypeId] TINYINT NOT NULL,
	[MarketItemStatusId] TINYINT NOT NULL, 
	[MarketItemFeatureId] TINYINT NOT NULL,
	[Title] VARCHAR(256) NOT NULL,
	[Description] VARCHAR(MAX) NOT NULL,
	[MainImage] VARCHAR(256) NULL, 
    [AskingPrice] DECIMAL(38, 8) NOT NULL, 
	[ReservePrice] DECIMAL(38, 8) NOT NULL,
	[LocationId] INT NOT NULL,
	[LocationRegion] VARCHAR(256) NULL,
	[AllowPickup] BIT NOT NULL,
    [PickupOnly] BIT NOT NULL, 
    [ShippingBuyerArrange] BIT NOT NULL, 
    [ShippingNational] BIT NOT NULL, 
    [ShippingInternational] BIT NOT NULL, 
    [ShippingNationalPrice] DECIMAL(38, 8) NOT NULL, 
    [ShippingNationalDetails] VARCHAR(256) NULL, 
    [ShippingInternationalPrice] DECIMAL(38, 8) NOT NULL, 
    [ShippingInternationalDetails] VARCHAR(256) NULL, 
    [CloseDate] DATETIME2 NOT NULL, 
    [Created] DATETIME2 NOT NULL, 
    CONSTRAINT [PK_MarketItem] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [FK_MarketItem_Category] FOREIGN KEY ([CategoryId]) REFERENCES [MarketCategory]([Id]),
    CONSTRAINT [FK_MarketItem_Status] FOREIGN KEY ([MarketItemStatusId]) REFERENCES [MarketItemStatus]([Id]),
	CONSTRAINT [FK_MarketItem_Type] FOREIGN KEY ([MarketItemTypeId]) REFERENCES [MarketItemType]([Id]),
	CONSTRAINT [FK_MarketItem_Feature] FOREIGN KEY ([MarketItemFeatureId]) REFERENCES [MarketItemFeature]([Id]),
	CONSTRAINT [FK_MarketItem_Location] FOREIGN KEY ([LocationId]) REFERENCES [Location]([Id]),
)
