//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Arbitrage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Arbitrage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Site.Resources.Arbitrage", typeof(Arbitrage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}({1}) Markets.
        /// </summary>
        public static string arbitrageCurrencyMarketHeadline {
            get {
                return ResourceManager.GetString("arbitrageCurrencyMarketHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string arbitrageCurrencySearchLabel {
            get {
                return ResourceManager.GetString("arbitrageCurrencySearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string arbitrageCurrencySearchPlaceholder {
            get {
                return ResourceManager.GetString("arbitrageCurrencySearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yarrrrrrrbitrage.
        /// </summary>
        public static string arbitrageHeadline {
            get {
                return ResourceManager.GetString("arbitrageHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use yaarbitrage to take advantage of a price difference between two or more markets, striking a combination of matching deals that capitalize upon the imbalance, the profit being the difference between the market prices..
        /// </summary>
        public static string arbitrageInfoText {
            get {
                return ResourceManager.GetString("arbitrageInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask.
        /// </summary>
        public static string arbitrageMarketAskLabel {
            get {
                return ResourceManager.GetString("arbitrageMarketAskLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Vol.
        /// </summary>
        public static string arbitrageMarketBaseVolLabel {
            get {
                return ResourceManager.GetString("arbitrageMarketBaseVolLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid.
        /// </summary>
        public static string arbitrageMarketBidLabel {
            get {
                return ResourceManager.GetString("arbitrageMarketBidLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string arbitrageMarketLastLabel {
            get {
                return ResourceManager.GetString("arbitrageMarketLastLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}/{2} market.
        /// </summary>
        public static string arbitrageMarketLink {
            get {
                return ResourceManager.GetString("arbitrageMarketLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string arbitrageMarketVolumeLabel {
            get {
                return ResourceManager.GetString("arbitrageMarketVolumeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbitrage.
        /// </summary>
        public static string arbitragePageTitle {
            get {
                return ResourceManager.GetString("arbitragePageTitle", resourceCulture);
            }
        }
    }
}
