//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Chat {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Chat() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Site.Resources.Chat", typeof(Chat).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban User.
        /// </summary>
        public static string banButton {
            get {
                return ResourceManager.GetString("banButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban Hammer.
        /// </summary>
        public static string banHeadline {
            get {
                return ResourceManager.GetString("banHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can ban a user from Chat, Tips or both.
        /// </summary>
        public static string banInfoText {
            get {
                return ResourceManager.GetString("banInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban Message.
        /// </summary>
        public static string banMessageLabel {
            get {
                return ResourceManager.GetString("banMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        public static string banSecondsLabel {
            get {
                return ResourceManager.GetString("banSecondsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban Type.
        /// </summary>
        public static string banTypeLabel {
            get {
                return ResourceManager.GetString("banTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (0 to unban).
        /// </summary>
        public static string banUnbanTimerLabel {
            get {
                return ResourceManager.GetString("banUnbanTimerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string banUserLabel {
            get {
                return ResourceManager.GetString("banUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Ignore.
        /// </summary>
        public static string chatIgnoreNotificationTitle {
            get {
                return ResourceManager.GetString("chatIgnoreNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string chatLoadingHeadline {
            get {
                return ResourceManager.GetString("chatLoadingHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login to troll.
        /// </summary>
        public static string chatLoginToTrollLink {
            get {
                return ResourceManager.GetString("chatLoginToTrollLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Trollbox Window.
        /// </summary>
        public static string chatOpenTrollboxWindowHint {
            get {
                return ResourceManager.GetString("chatOpenTrollboxWindowHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string chatPageTitle {
            get {
                return ResourceManager.GetString("chatPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this post?.
        /// </summary>
        public static string chatRemovePostQuestion {
            get {
                return ResourceManager.GetString("chatRemovePostQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Post?.
        /// </summary>
        public static string chatRemovePostQuestionTitle {
            get {
                return ResourceManager.GetString("chatRemovePostQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Karma.
        /// </summary>
        public static string chatSendKarmaNotificationTitle {
            get {
                return ResourceManager.GetString("chatSendKarmaNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip Ignore.
        /// </summary>
        public static string chatTipIgnoreNotificationTitle {
            get {
                return ResourceManager.GetString("chatTipIgnoreNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip Karma.
        /// </summary>
        public static string chatTipKarmaNotificationTitle {
            get {
                return ResourceManager.GetString("chatTipKarmaNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trollbox.
        /// </summary>
        public static string chatTrollbox {
            get {
                return ResourceManager.GetString("chatTrollbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trollbox Rules.
        /// </summary>
        public static string chatTrollboxRulesHint {
            get {
                return ResourceManager.GetString("chatTrollboxRulesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Online.
        /// </summary>
        public static string chatUsersOnline {
            get {
                return ResourceManager.GetString("chatUsersOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Emoticon.
        /// </summary>
        public static string emoticonAddButton {
            get {
                return ResourceManager.GetString("emoticonAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string emoticonCategoryLabel {
            get {
                return ResourceManager.GetString("emoticonCategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Categories.
        /// </summary>
        public static string emoticonCategoryPlaceholder {
            get {
                return ResourceManager.GetString("emoticonCategoryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Code.
        /// </summary>
        public static string emoticonCodeLabel {
            get {
                return ResourceManager.GetString("emoticonCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trollbox Emoticons.
        /// </summary>
        public static string emoticonHeadline {
            get {
                return ResourceManager.GetString("emoticonHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string emoticonNameLabel {
            get {
                return ResourceManager.GetString("emoticonNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string emoticonSearchLabel {
            get {
                return ResourceManager.GetString("emoticonSearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty message..
        /// </summary>
        public static string errorEmptyMessage {
            get {
                return ResourceManager.GetString("errorEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknow error occured..
        /// </summary>
        public static string errorUnknownMessage {
            get {
                return ResourceManager.GetString("errorUnknownMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat user not found..
        /// </summary>
        public static string errorUserNotFoundMessage {
            get {
                return ResourceManager.GetString("errorUserNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trollbox Rules.
        /// </summary>
        public static string rulesHeadline {
            get {
                return ResourceManager.GetString("rulesHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ol style=&quot;font-size:13px&quot;&gt;
        ///	&lt;li&gt;Logging a Support Ticket about someone not liking you in chat&amp;nbsp;or an equally ridiculous reason will result in Trollbox Perma-Ban&lt;/li&gt;
        ///	&lt;li&gt;Logging a Support Ticket about getting Banned or PayBanned will result in Trollbox Perma-Ban&lt;/li&gt;
        ///	&lt;li&gt;Logging a Support Ticket about being on someone&apos;s ignore list or tip ignore list will result in Trollbox Perma-Ban&lt;/li&gt;
        ///	&lt;li&gt;Logging a Support Ticket complaining that you only made 0.0000xxxx in tips today will result in Trollbox [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RulesHtml {
            get {
                return ResourceManager.GetString("RulesHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please follow the rules below and respect all languages of trollers.
        /// </summary>
        public static string rulesInfoText {
            get {
                return ResourceManager.GetString("rulesInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string settingsHeadline {
            get {
                return ResourceManager.GetString("settingsHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (ages ago...).
        /// </summary>
        public static string sinceAgesLabel {
            get {
                return ResourceManager.GetString("sinceAgesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (an hour ago).
        /// </summary>
        public static string sinceHourLabel {
            get {
                return ResourceManager.GetString("sinceHourLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} hours ago).
        /// </summary>
        public static string sinceHoursLabel {
            get {
                return ResourceManager.GetString("sinceHoursLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (an minute ago).
        /// </summary>
        public static string sinceMinuteLabel {
            get {
                return ResourceManager.GetString("sinceMinuteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} minutes ago).
        /// </summary>
        public static string sinceMinutesLabel {
            get {
                return ResourceManager.GetString("sinceMinutesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (just now).
        /// </summary>
        public static string sinceSecondLabel {
            get {
                return ResourceManager.GetString("sinceSecondLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} seconds ago).
        /// </summary>
        public static string sinceSecondsLabel {
            get {
                return ResourceManager.GetString("sinceSecondsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give {{ChatHandle}} +1 karma for this.
        /// </summary>
        public static string templateGiveKarmaHint {
            get {
                return ResourceManager.GetString("templateGiveKarmaHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban Hammer.
        /// </summary>
        public static string templateHammerHint {
            get {
                return ResourceManager.GetString("templateHammerHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{ChatHandle}} has {{KarmaTotal}} karma points.
        /// </summary>
        public static string templateHasKarmaHint {
            get {
                return ResourceManager.GetString("templateHasKarmaHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user to chat ignore list.
        /// </summary>
        public static string templateIgnoreHint {
            get {
                return ResourceManager.GetString("templateIgnoreHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Post.
        /// </summary>
        public static string templateRemovePostHint {
            get {
                return ResourceManager.GetString("templateRemovePostHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user to tipping ignore list.
        /// </summary>
        public static string templateTippingIgnoreHint {
            get {
                return ResourceManager.GetString("templateTippingIgnoreHint", resourceCulture);
            }
        }
    }
}
