//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Exchange {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exchange() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Site.Resources.Exchange", typeof(Exchange).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string balanceAvailableColumn {
            get {
                return ResourceManager.GetString("balanceAvailableColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount available to trade.
        /// </summary>
        public static string balanceAvailableColumnHint {
            get {
                return ResourceManager.GetString("balanceAvailableColumnHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coin.
        /// </summary>
        public static string balanceCoinColumn {
            get {
                return ResourceManager.GetString("balanceCoinColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No balances found..
        /// </summary>
        public static string balanceEmptyListMessage {
            get {
                return ResourceManager.GetString("balanceEmptyListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est..
        /// </summary>
        public static string balanceEstimatedColumn {
            get {
                return ResourceManager.GetString("balanceEstimatedColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated BTC value.
        /// </summary>
        public static string balanceEstimatedColumnHint {
            get {
                return ResourceManager.GetString("balanceEstimatedColumnHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Favorites Only.
        /// </summary>
        public static string balanceFavoritesOnlyLabel {
            get {
                return ResourceManager.GetString("balanceFavoritesOnlyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Zero Balances.
        /// </summary>
        public static string balanceHideZeroBalancesLabel {
            get {
                return ResourceManager.GetString("balanceHideZeroBalancesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string balanceOrdersColumn {
            get {
                return ResourceManager.GetString("balanceOrdersColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount held for open orders.
        /// </summary>
        public static string balanceOrdersColumnHint {
            get {
                return ResourceManager.GetString("balanceOrdersColumnHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search balances....
        /// </summary>
        public static string balanceSearchPlaceholder {
            get {
                return ResourceManager.GetString("balanceSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string buyAmountLabel {
            get {
                return ResourceManager.GetString("buyAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string buyAvailableLabel {
            get {
                return ResourceManager.GetString("buyAvailableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string buyButton {
            get {
                return ResourceManager.GetString("buyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee.
        /// </summary>
        public static string buyFeeLabel {
            get {
                return ResourceManager.GetString("buyFeeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string buyHeadline {
            get {
                return ResourceManager.GetString("buyHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum trade.
        /// </summary>
        public static string buyMinimumTradeLabel {
            get {
                return ResourceManager.GetString("buyMinimumTradeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string buyPriceLabel {
            get {
                return ResourceManager.GetString("buyPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string buySumLabel {
            get {
                return ResourceManager.GetString("buySumLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string buyTotalLabel {
            get {
                return ResourceManager.GetString("buyTotalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange.
        /// </summary>
        public static string exchangeTitle {
            get {
                return ResourceManager.GetString("exchangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Markets.
        /// </summary>
        public static string featuredHeadline {
            get {
                return ResourceManager.GetString("featuredHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string featuredInfoLabel {
            get {
                return ResourceManager.GetString("featuredInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string featuredWebsiteLabel {
            get {
                return ResourceManager.GetString("featuredWebsiteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string historyAmountColumn {
            get {
                return ResourceManager.GetString("historyAmountColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Orders.
        /// </summary>
        public static string historyBuyHeadline {
            get {
                return ResourceManager.GetString("historyBuyHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No buy orders..
        /// </summary>
        public static string historyBuyOrdersEmptyList {
            get {
                return ResourceManager.GetString("historyBuyOrdersEmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No market history..
        /// </summary>
        public static string historyMarketEmtpyList {
            get {
                return ResourceManager.GetString("historyMarketEmtpyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market History.
        /// </summary>
        public static string historyMarketHeadline {
            get {
                return ResourceManager.GetString("historyMarketHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Market History.
        /// </summary>
        public static string historyMyMarketHeadline {
            get {
                return ResourceManager.GetString("historyMyMarketHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel All.
        /// </summary>
        public static string historyMyOpenOrdersCancelLink {
            get {
                return ResourceManager.GetString("historyMyOpenOrdersCancelLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no open orders..
        /// </summary>
        public static string historyMyOpenOrdersEmtpyList {
            get {
                return ResourceManager.GetString("historyMyOpenOrdersEmtpyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Open Orders.
        /// </summary>
        public static string historyMyOpenOrdersHeadline {
            get {
                return ResourceManager.GetString("historyMyOpenOrdersHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no order history..
        /// </summary>
        public static string historyMyOrdersEmtpyList {
            get {
                return ResourceManager.GetString("historyMyOrdersEmtpyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string historyPriceColumn {
            get {
                return ResourceManager.GetString("historyPriceColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining.
        /// </summary>
        public static string historyRemainingColumn {
            get {
                return ResourceManager.GetString("historyRemainingColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sell orders..
        /// </summary>
        public static string historySellOrdersEmptyList {
            get {
                return ResourceManager.GetString("historySellOrdersEmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Orders.
        /// </summary>
        public static string historySellTitle {
            get {
                return ResourceManager.GetString("historySellTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string historySumColumn {
            get {
                return ResourceManager.GetString("historySumColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        public static string historyTimestampColumn {
            get {
                return ResourceManager.GetString("historyTimestampColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string historyTotalColumn {
            get {
                return ResourceManager.GetString("historyTotalColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string historyTypeColumn {
            get {
                return ResourceManager.GetString("historyTypeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        public static string infoBaseLabel {
            get {
                return ResourceManager.GetString("infoBaseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart.
        /// </summary>
        public static string infoChartButton {
            get {
                return ResourceManager.GetString("infoChartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Available.
        /// </summary>
        public static string infoChartNoDataMessage {
            get {
                return ResourceManager.GetString("infoChartNoDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candlestick.
        /// </summary>
        public static string infoChartSettingsCandlestickLabel {
            get {
                return ResourceManager.GetString("infoChartSettingsCandlestickLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMA 1 period.
        /// </summary>
        public static string infoChartSettingsEma1PeriodLabel {
            get {
                return ResourceManager.GetString("infoChartSettingsEma1PeriodLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMA 2 period.
        /// </summary>
        public static string infoChartSettingsEma2PeriodLabel {
            get {
                return ResourceManager.GetString("infoChartSettingsEma2PeriodLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fibonacci Lines.
        /// </summary>
        public static string infoChartSettingsFibonacciLinesLabel {
            get {
                return ResourceManager.GetString("infoChartSettingsFibonacciLinesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Settings.
        /// </summary>
        public static string infoChartSettingsHeadline {
            get {
                return ResourceManager.GetString("infoChartSettingsHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histogram.
        /// </summary>
        public static string infoChartSettingsHistogramLabel {
            get {
                return ResourceManager.GetString("infoChartSettingsHistogramLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MACD.
        /// </summary>
        public static string infoChartSettingsMacdLabel {
            get {
                return ResourceManager.GetString("infoChartSettingsMacdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal.
        /// </summary>
        public static string infoChartSettingsSignalLabel {
            get {
                return ResourceManager.GetString("infoChartSettingsSignalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMA period.
        /// </summary>
        public static string infoChartSettingsSmaPeriodLabel {
            get {
                return ResourceManager.GetString("infoChartSettingsSmaPeriodLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StockPrice.
        /// </summary>
        public static string infoChartSettingsStockPriceLabel {
            get {
                return ResourceManager.GetString("infoChartSettingsStockPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string infoChartSettingsVolumeLabel {
            get {
                return ResourceManager.GetString("infoChartSettingsVolumeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string infoCloseLabel {
            get {
                return ResourceManager.GetString("infoCloseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string infoDateLabel {
            get {
                return ResourceManager.GetString("infoDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderBook.
        /// </summary>
        public static string infoDepthButton {
            get {
                return ResourceManager.GetString("infoDepthButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orderbook Depth.
        /// </summary>
        public static string infoDepthHeadline {
            get {
                return ResourceManager.GetString("infoDepthHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string infoDepthSettingsAutoLabel {
            get {
                return ResourceManager.GetString("infoDepthSettingsAutoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth Calculation.
        /// </summary>
        public static string infoDepthSettingsHeadline {
            get {
                return ResourceManager.GetString("infoDepthSettingsHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth.
        /// </summary>
        public static string infoDepthTooltipDepthLabel {
            get {
                return ResourceManager.GetString("infoDepthTooltipDepthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Depth.
        /// </summary>
        public static string infoDepthTooltipHeadline {
            get {
                return ResourceManager.GetString("infoDepthTooltipHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string infoDepthTooltipPriceLabel {
            get {
                return ResourceManager.GetString("infoDepthTooltipPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string infoDepthTooltipVolumeLabel {
            get {
                return ResourceManager.GetString("infoDepthTooltipVolumeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution.
        /// </summary>
        public static string infoDistributionButton {
            get {
                return ResourceManager.GetString("infoDistributionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Distribution.
        /// </summary>
        public static string infoDistributionHeadline {
            get {
                return ResourceManager.GetString("infoDistributionHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Distribution.
        /// </summary>
        public static string infoDistributionSettingsHeadline {
            get {
                return ResourceManager.GetString("infoDistributionSettingsHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top {0}.
        /// </summary>
        public static string infoDistributionSettingsTopLabel {
            get {
                return ResourceManager.GetString("infoDistributionSettingsTopLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string infoHighLabel {
            get {
                return ResourceManager.GetString("infoHighLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hist.
        /// </summary>
        public static string infoHistLabel {
            get {
                return ResourceManager.GetString("infoHistLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string infoLowLabel {
            get {
                return ResourceManager.GetString("infoLowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MACD.
        /// </summary>
        public static string infoMacdLabel {
            get {
                return ResourceManager.GetString("infoMacdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string infoOpenLabel {
            get {
                return ResourceManager.GetString("infoOpenLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string infoPriceLabel {
            get {
                return ResourceManager.GetString("infoPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Profile.
        /// </summary>
        public static string infoSaveProfileButton {
            get {
                return ResourceManager.GetString("infoSaveProfileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Failed.
        /// </summary>
        public static string infoSettingsFailedMessage {
            get {
                return ResourceManager.GetString("infoSettingsFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Saved.
        /// </summary>
        public static string infoSettingsSavedMessage {
            get {
                return ResourceManager.GetString("infoSettingsSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sig:.
        /// </summary>
        public static string infoSigLabel {
            get {
                return ResourceManager.GetString("infoSigLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string infoStatisticsChangeLabel {
            get {
                return ResourceManager.GetString("infoStatisticsChangeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string infoStatisticsHighLabel {
            get {
                return ResourceManager.GetString("infoStatisticsHighLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last price.
        /// </summary>
        public static string infoStatisticsLastPriceLabel {
            get {
                return ResourceManager.GetString("infoStatisticsLastPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string infoStatisticsLowLabel {
            get {
                return ResourceManager.GetString("infoStatisticsLowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24 Hours.
        /// </summary>
        public static string infoStatisticsTitle {
            get {
                return ResourceManager.GetString("infoStatisticsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string infoStatisticsTitle2 {
            get {
                return ResourceManager.GetString("infoStatisticsTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string infoStatisticsVolumeLabel {
            get {
                return ResourceManager.GetString("infoStatisticsVolumeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vol.
        /// </summary>
        public static string infoVolLabel {
            get {
                return ResourceManager.GetString("infoVolLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market.
        /// </summary>
        public static string marketPageTitle {
            get {
                return ResourceManager.GetString("marketPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +/-.
        /// </summary>
        public static string marketsChangeColumn {
            get {
                return ResourceManager.GetString("marketsChangeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24hr price change %.
        /// </summary>
        public static string marketsChangeColumnHint {
            get {
                return ResourceManager.GetString("marketsChangeColumnHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No markets found..
        /// </summary>
        public static string marketsEmptyListMessage {
            get {
                return ResourceManager.GetString("marketsEmptyListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading markets....
        /// </summary>
        public static string marketsLoadingMessage {
            get {
                return ResourceManager.GetString("marketsLoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market.
        /// </summary>
        public static string marketsMarketColumn {
            get {
                return ResourceManager.GetString("marketsMarketColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string marketsPriceColumn {
            get {
                return ResourceManager.GetString("marketsPriceColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last price.
        /// </summary>
        public static string marketsPriceColumnHint {
            get {
                return ResourceManager.GetString("marketsPriceColumnHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search markets....
        /// </summary>
        public static string marketsSearchPlaceholder {
            get {
                return ResourceManager.GetString("marketsSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string marketsShowFavoritesOnlyLabel {
            get {
                return ResourceManager.GetString("marketsShowFavoritesOnlyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vol..
        /// </summary>
        public static string marketsVolColumn {
            get {
                return ResourceManager.GetString("marketsVolColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24hr base volume.
        /// </summary>
        public static string marketsVolColumnHint {
            get {
                return ResourceManager.GetString("marketsVolColumnHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balances.
        /// </summary>
        public static string menuBalances {
            get {
                return ResourceManager.GetString("menuBalances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string menuChat {
            get {
                return ResourceManager.GetString("menuChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markets.
        /// </summary>
        public static string menuMarkets {
            get {
                return ResourceManager.GetString("menuMarkets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string menuOrders {
            get {
                return ResourceManager.GetString("menuOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no open orders..
        /// </summary>
        public static string ordersEmptyListMessage {
            get {
                return ResourceManager.GetString("ordersEmptyListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pair.
        /// </summary>
        public static string ordersPairColumn {
            get {
                return ResourceManager.GetString("ordersPairColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string ordersRateColumn {
            get {
                return ResourceManager.GetString("ordersRateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price of order.
        /// </summary>
        public static string ordersRateColumnHint {
            get {
                return ResourceManager.GetString("ordersRateColumnHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining.
        /// </summary>
        public static string ordersRemainingColumn {
            get {
                return ResourceManager.GetString("ordersRemainingColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coins remaining in order.
        /// </summary>
        public static string ordersRemainingColumnHint {
            get {
                return ResourceManager.GetString("ordersRemainingColumnHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search orders....
        /// </summary>
        public static string ordersSearchPlaceholder {
            get {
                return ResourceManager.GetString("ordersSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string ordersTypeColumn {
            get {
                return ResourceManager.GetString("ordersTypeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string sellAmountLabel {
            get {
                return ResourceManager.GetString("sellAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string sellAvailableLabel {
            get {
                return ResourceManager.GetString("sellAvailableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell.
        /// </summary>
        public static string sellButton {
            get {
                return ResourceManager.GetString("sellButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee.
        /// </summary>
        public static string sellFeeLabel {
            get {
                return ResourceManager.GetString("sellFeeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell.
        /// </summary>
        public static string sellHeadline {
            get {
                return ResourceManager.GetString("sellHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum trade.
        /// </summary>
        public static string sellMinimumTradeLabel {
            get {
                return ResourceManager.GetString("sellMinimumTradeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string sellPriceLabel {
            get {
                return ResourceManager.GetString("sellPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string sellSumLabel {
            get {
                return ResourceManager.GetString("sellSumLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string sellTotalLabel {
            get {
                return ResourceManager.GetString("sellTotalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string summaryChangeColumn {
            get {
                return ResourceManager.GetString("summaryChangeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string summaryCurrencyColumn {
            get {
                return ResourceManager.GetString("summaryCurrencyColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Summary (24hr).
        /// </summary>
        public static string summaryHeadline {
            get {
                return ResourceManager.GetString("summaryHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string summaryHighColumn {
            get {
                return ResourceManager.GetString("summaryHighColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string summaryLastColumn {
            get {
                return ResourceManager.GetString("summaryLastColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string summaryLowColumn {
            get {
                return ResourceManager.GetString("summaryLowColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market.
        /// </summary>
        public static string summaryMarketColumn {
            get {
                return ResourceManager.GetString("summaryMarketColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string summaryVolumeColumn {
            get {
                return ResourceManager.GetString("summaryVolumeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string topChangeColumn {
            get {
                return ResourceManager.GetString("topChangeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Markets.
        /// </summary>
        public static string topHeadline {
            get {
                return ResourceManager.GetString("topHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string topHighColumn {
            get {
                return ResourceManager.GetString("topHighColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string topLowColumn {
            get {
                return ResourceManager.GetString("topLowColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market.
        /// </summary>
        public static string topMarketColumn {
            get {
                return ResourceManager.GetString("topMarketColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string topTotalColumn {
            get {
                return ResourceManager.GetString("topTotalColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string topVolumeColumn {
            get {
                return ResourceManager.GetString("topVolumeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy order submitted.
        /// </summary>
        public static string tradeBuyOrderSubmittedMessage {
            get {
                return ResourceManager.GetString("tradeBuyOrderSubmittedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient {0} funds..
        /// </summary>
        public static string tradeInsufficientFundsError {
            get {
                return ResourceManager.GetString("tradeInsufficientFundsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid trade amount, Maximum single trade is {0}.
        /// </summary>
        public static string tradeMaxAmountError {
            get {
                return ResourceManager.GetString("tradeMaxAmountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid trade price, maximum price is {0}.
        /// </summary>
        public static string tradeMaxPriceError {
            get {
                return ResourceManager.GetString("tradeMaxPriceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid trade price, minimum price is {0}.
        /// </summary>
        public static string tradeMinPriceError {
            get {
                return ResourceManager.GetString("tradeMinPriceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your trade total must be at least {0} {1}.
        /// </summary>
        public static string tradeMinTotalError {
            get {
                return ResourceManager.GetString("tradeMinTotalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market not found..
        /// </summary>
        public static string tradeNoMarketError {
            get {
                return ResourceManager.GetString("tradeNoMarketError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Notification.
        /// </summary>
        public static string tradeNotificationTitle {
            get {
                return ResourceManager.GetString("tradeNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell order submitted.
        /// </summary>
        public static string tradeSellOrderSubmittedMessage {
            get {
                return ResourceManager.GetString("tradeSellOrderSubmittedMessage", resourceCulture);
            }
        }
    }
}
