//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Forum {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Forum() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Site.Resources.Forum", typeof(Forum).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Category.
        /// </summary>
        public static string categoryCreateButton {
            get {
                return ResourceManager.GetString("categoryCreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new category.
        /// </summary>
        public static string categoryCreateHeadline {
            get {
                return ResourceManager.GetString("categoryCreateHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Category.
        /// </summary>
        public static string categoryDeleteButton {
            get {
                return ResourceManager.GetString("categoryDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this category including all thread &amp; posts within?.
        /// </summary>
        public static string categoryDeleteQuestion {
            get {
                return ResourceManager.GetString("categoryDeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Category.
        /// </summary>
        public static string categoryDeleteQuestionTitle {
            get {
                return ResourceManager.GetString("categoryDeleteQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string categoryDescriptionLabel {
            get {
                return ResourceManager.GetString("categoryDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Category.
        /// </summary>
        public static string categoryEditButton {
            get {
                return ResourceManager.GetString("categoryEditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following category #{0} could not be found..
        /// </summary>
        public static string categoryNotFoundErrorMessage {
            get {
                return ResourceManager.GetString("categoryNotFoundErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Not Found.
        /// </summary>
        public static string categoryNotFoundErrorTitle {
            get {
                return ResourceManager.GetString("categoryNotFoundErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string categoryOrderLabel {
            get {
                return ResourceManager.GetString("categoryOrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string categoryTitleLabel {
            get {
                return ResourceManager.GetString("categoryTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Category.
        /// </summary>
        public static string categoryUpdateHeadline {
            get {
                return ResourceManager.GetString("categoryUpdateHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Forum.
        /// </summary>
        public static string forumCreateForumButton {
            get {
                return ResourceManager.GetString("forumCreateForumButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new forum.
        /// </summary>
        public static string forumCreateHeadline {
            get {
                return ResourceManager.GetString("forumCreateHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Forum.
        /// </summary>
        public static string forumDeleteForumButton {
            get {
                return ResourceManager.GetString("forumDeleteForumButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this forum and all categories/threads?.
        /// </summary>
        public static string forumDeleteForumQuestion {
            get {
                return ResourceManager.GetString("forumDeleteForumQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Forum.
        /// </summary>
        public static string forumDeleteForumQuestionTitle {
            get {
                return ResourceManager.GetString("forumDeleteForumQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum #{0} not found..
        /// </summary>
        public static string forumDeleteNotFoundError {
            get {
                return ResourceManager.GetString("forumDeleteNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string forumDescriptionLabel {
            get {
                return ResourceManager.GetString("forumDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Forum.
        /// </summary>
        public static string forumEditForumButton {
            get {
                return ResourceManager.GetString("forumEditForumButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cryptopia Forums.
        /// </summary>
        public static string forumHeadline {
            get {
                return ResourceManager.GetString("forumHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Posts.
        /// </summary>
        public static string forumLastPostsHeadline {
            get {
                return ResourceManager.GetString("forumLastPostsHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string forumOrderLabel {
            get {
                return ResourceManager.GetString("forumOrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum.
        /// </summary>
        public static string forumPageTitle {
            get {
                return ResourceManager.GetString("forumPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forums.
        /// </summary>
        public static string forumPathRootLink {
            get {
                return ResourceManager.GetString("forumPathRootLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        public static string forumPathSearchLink {
            get {
                return ResourceManager.GetString("forumPathSearchLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string forumSearchFieldPlaceholder {
            get {
                return ResourceManager.GetString("forumSearchFieldPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Posts.
        /// </summary>
        public static string forumSearchPostCheckbox {
            get {
                return ResourceManager.GetString("forumSearchPostCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string forumTitleLabel {
            get {
                return ResourceManager.GetString("forumTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Forum.
        /// </summary>
        public static string forumUpdateHeadline {
            get {
                return ResourceManager.GetString("forumUpdateHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts.
        /// </summary>
        public static string postCountLabel {
            get {
                return ResourceManager.GetString("postCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string postDeleteButton {
            get {
                return ResourceManager.GetString("postDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to delete this post..
        /// </summary>
        public static string postDeletePermitionErrorMessage {
            get {
                return ResourceManager.GetString("postDeletePermitionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        public static string postDeletePermitionErrorTitle {
            get {
                return ResourceManager.GetString("postDeletePermitionErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this post?.
        /// </summary>
        public static string postDeleteQuestion {
            get {
                return ResourceManager.GetString("postDeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Post.
        /// </summary>
        public static string postDeleteQuestionTitle {
            get {
                return ResourceManager.GetString("postDeleteQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string postEditButton {
            get {
                return ResourceManager.GetString("postEditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string postMessageLabel {
            get {
                return ResourceManager.GetString("postMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not find the post you are looking for.
        /// </summary>
        public static string postNotFoundErrorMessage {
            get {
                return ResourceManager.GetString("postNotFoundErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string postNotFoundErrorTitle {
            get {
                return ResourceManager.GetString("postNotFoundErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote.
        /// </summary>
        public static string postQuoteButton {
            get {
                return ResourceManager.GetString("postQuoteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RE.
        /// </summary>
        public static string postReplayHeadlinePrefix {
            get {
                return ResourceManager.GetString("postReplayHeadlinePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        public static string postReplyButton {
            get {
                return ResourceManager.GetString("postReplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string postReportButton {
            get {
                return ResourceManager.GetString("postReportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string postReportMessageLabel {
            get {
                return ResourceManager.GetString("postReportMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to edit this post..
        /// </summary>
        public static string postUpdatePermitionErrorMessage {
            get {
                return ResourceManager.GetString("postUpdatePermitionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        public static string postUpdatePermitionErrorTitle {
            get {
                return ResourceManager.GetString("postUpdatePermitionErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found..
        /// </summary>
        public static string searchEmptyListMessage {
            get {
                return ResourceManager.GetString("searchEmptyListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum Search.
        /// </summary>
        public static string searchPageTitle {
            get {
                return ResourceManager.GetString("searchPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing results {0} to {1} of {2}.
        /// </summary>
        public static string searchPaggerMessage {
            get {
                return ResourceManager.GetString("searchPaggerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threads.
        /// </summary>
        public static string threadCountLabel {
            get {
                return ResourceManager.GetString("threadCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Thread.
        /// </summary>
        public static string threadCreateButton {
            get {
                return ResourceManager.GetString("threadCreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Thread.
        /// </summary>
        public static string threadDeleteButton {
            get {
                return ResourceManager.GetString("threadDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this thread?.
        /// </summary>
        public static string threadDeleteQuestion {
            get {
                return ResourceManager.GetString("threadDeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Thread.
        /// </summary>
        public static string threadDeleteQuestionTitle {
            get {
                return ResourceManager.GetString("threadDeleteQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string threadEditButton {
            get {
                return ResourceManager.GetString("threadEditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited.
        /// </summary>
        public static string threadEditedLabel {
            get {
                return ResourceManager.GetString("threadEditedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread.
        /// </summary>
        public static string threadLabel {
            get {
                return ResourceManager.GetString("threadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Post.
        /// </summary>
        public static string threadLastPostLabel {
            get {
                return ResourceManager.GetString("threadLastPostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Update.
        /// </summary>
        public static string threadLastUpdateLabel {
            get {
                return ResourceManager.GetString("threadLastUpdateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread Content.
        /// </summary>
        public static string threadMessageLabel {
            get {
                return ResourceManager.GetString("threadMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not find the thread you are looking for.
        /// </summary>
        public static string threadNotFoundErrorMessage {
            get {
                return ResourceManager.GetString("threadNotFoundErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread Not Found.
        /// </summary>
        public static string threadNotFoundErrorTitle {
            get {
                return ResourceManager.GetString("threadNotFoundErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing posts {0} to {1} of {2}.
        /// </summary>
        public static string threadPaggerMessage {
            get {
                return ResourceManager.GetString("threadPaggerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Thread.
        /// </summary>
        public static string threadPinHint {
            get {
                return ResourceManager.GetString("threadPinHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted.
        /// </summary>
        public static string threadPostedLabel {
            get {
                return ResourceManager.GetString("threadPostedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply to thread.
        /// </summary>
        public static string threadReplyButton {
            get {
                return ResourceManager.GetString("threadReplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Post.
        /// </summary>
        public static string threadReportPostHint {
            get {
                return ResourceManager.GetString("threadReportPostHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Time.
        /// </summary>
        public static string threadServerTimeLabel {
            get {
                return ResourceManager.GetString("threadServerTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread Title.
        /// </summary>
        public static string threadTitleLabel {
            get {
                return ResourceManager.GetString("threadTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to edit this thread..
        /// </summary>
        public static string threadUpdatePermitionErrorMessage {
            get {
                return ResourceManager.GetString("threadUpdatePermitionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        public static string threadUpdatePermitionErrorTitle {
            get {
                return ResourceManager.GetString("threadUpdatePermitionErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string threadUserCountryLabel {
            get {
                return ResourceManager.GetString("threadUserCountryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string threadUserGenderLabel {
            get {
                return ResourceManager.GetString("threadUserGenderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string userCountryUnknown {
            get {
                return ResourceManager.GetString("userCountryUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string userGenderUnknown {
            get {
                return ResourceManager.GetString("userGenderUnknown", resourceCulture);
            }
        }
    }
}
