//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Site.Resources.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Request.
        /// </summary>
        public static string contactButton {
            get {
                return ResourceManager.GetString("contactButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply Email.
        /// </summary>
        public static string contactEmailLabel {
            get {
                return ResourceManager.GetString("contactEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must supply a valid reply email address.
        /// </summary>
        public static string contactEmailRequiredError {
            get {
                return ResourceManager.GetString("contactEmailRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send email, please try again..
        /// </summary>
        public static string contactFailedMessage {
            get {
                return ResourceManager.GetString("contactFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string contactMessageLabel {
            get {
                return ResourceManager.GetString("contactMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must supply a message.
        /// </summary>
        public static string contactMessageRequiredError {
            get {
                return ResourceManager.GetString("contactMessageRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string contactPageTitle {
            get {
                return ResourceManager.GetString("contactPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid reCaptcha.
        /// </summary>
        public static string contactReCaptchaError {
            get {
                return ResourceManager.GetString("contactReCaptchaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending request....
        /// </summary>
        public static string contactSendingMessage {
            get {
                return ResourceManager.GetString("contactSendingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string contactSubjectLabel {
            get {
                return ResourceManager.GetString("contactSubjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must supply a message subject.
        /// </summary>
        public static string contactSubjectRequiredError {
            get {
                return ResourceManager.GetString("contactSubjectRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact request successfully sent, a support representative will be in touch shortly..
        /// </summary>
        public static string contactSuccessMessage {
            get {
                return ResourceManager.GetString("contactSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have any questions about the site? &lt;br/&gt; Your questions and comments are important to us..
        /// </summary>
        public static string contactSummaryHtml {
            get {
                return ResourceManager.GetString("contactSummaryHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;Cryptopia Limited.&lt;/h2&gt;
        ///&lt;hr /&gt;
        ///&lt;p&gt;Cryptopia, written from scratch and designed from the ground up to be a by the users for the users one stop hub for all things cryptocurrency related. We believe that in order for cryptocurrencies to become widely adopted and prosper they need to be easily accesible, user friendly, and above all usable for actual goods and services. We aim to not just be another exchange, but to innovate and focus on the user experience, and ultimately make cryptocurrencies more acces [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 109 Montreal St, Sydenham, Christchurch 8023, New Zealand.
        /// </summary>
        public static string homeContactAddressText {
            get {
                return ResourceManager.GetString("homeContactAddressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us today:.
        /// </summary>
        public static string homeContactHeadline {
            get {
                return ResourceManager.GetString("homeContactHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade &amp; Exchange.
        /// </summary>
        public static string homeExchangeHeadline {
            get {
                return ResourceManager.GetString("homeExchangeHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Cryptopia exchange is a powerful currency trading platform..
        /// </summary>
        public static string homeExchangeLine1Text {
            get {
                return ResourceManager.GetString("homeExchangeLine1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit, trade, and withdraw Bitcoin, Litecoin, and over 400 other crypto currencies..
        /// </summary>
        public static string homeExchangeLine2Text {
            get {
                return ResourceManager.GetString("homeExchangeLine2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert New Zealand dollars to crypto by despositing to NZDt, and trading it for the coins of your choice..
        /// </summary>
        public static string homeExchangeLine3Text {
            get {
                return ResourceManager.GetString("homeExchangeLine3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange.
        /// </summary>
        public static string homeExchangeLink {
            get {
                return ResourceManager.GetString("homeExchangeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forums.
        /// </summary>
        public static string homeForumsLink {
            get {
                return ResourceManager.GetString("homeForumsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy &amp; Sell.
        /// </summary>
        public static string homeMarketplaceHeadline {
            get {
                return ResourceManager.GetString("homeMarketplaceHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Cryptopia marketplace lets you sell anything, to anyone, anywhere in the world in exchange for cryptocurrency..
        /// </summary>
        public static string homeMarketplaceLine1Text {
            get {
                return ResourceManager.GetString("homeMarketplaceLine1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy and sell items free of charge. Make sales via auction or classified listing. Start using your crypto today..
        /// </summary>
        public static string homeMarketplaceLine2Text {
            get {
                return ResourceManager.GetString("homeMarketplaceLine2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketplace.
        /// </summary>
        public static string homeMarketplaceLink {
            get {
                return ResourceManager.GetString("homeMarketplaceLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} to crypto.
        /// </summary>
        public static string homeNZD2CryptoLink {
            get {
                return ResourceManager.GetString("homeNZD2CryptoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security &amp; Support.
        /// </summary>
        public static string homeSupportHeadline {
            get {
                return ResourceManager.GetString("homeSupportHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join a trusted community built around a passion for cryptocurrency..
        /// </summary>
        public static string homeSupportLine1Text {
            get {
                return ResourceManager.GetString("homeSupportLine1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn the market from our News, CoinInfo, Arbitrage, and Forum sections..
        /// </summary>
        public static string homeSupportLine2Text {
            get {
                return ResourceManager.GetString("homeSupportLine2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay safe with market-leading two-factor security options, including Cryptopia hardware dongles..
        /// </summary>
        public static string homeSupportLine3Text {
            get {
                return ResourceManager.GetString("homeSupportLine3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string homeTitle {
            get {
                return ResourceManager.GetString("homeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;Privacy &amp; Security&lt;/h2&gt;
        ///&lt;hr /&gt;
        ///&lt;h4 style=&quot;font-weight:bolder&quot;&gt;Cryptopia Limited Privacy Policy&lt;/h4&gt;
        ///&lt;p&gt;
        ///	This web site is owned and operated by Cryptopia Ltd and will be referred to as &quot;We&quot;, &quot;our&quot; and &quot;us&quot; in this Internet Privacy Policy. By using this site, you agree to the Internet Privacy Policy of this web site (&quot;the web site&quot;), which is set out on this web site page. The Internet Privacy Policy relates to the collection and use of personal information you may supply to us through your conduct o [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string privacyTitle {
            get {
                return ResourceManager.GetString("privacyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;Terms &amp; Conditions &lt;/h2&gt;
        ///&lt;hr /&gt;
        ///&lt;p&gt;
        ///	&lt;span style=&quot;font-size: larger; font-weight: bolder&quot;&gt;Website Terms of Use &lt;/span&gt;
        ///	&lt;br /&gt;
        ///	This website (&quot;site&quot;) is operated by Cryptopia Limited (referred to on this site as &quot;the Company, “Cryptopia”, “Cryptopia Limited”, “Cryptopia Ltd”, &quot;we&quot;, &quot;us&quot; or &quot;our&quot;). Your use of this site is governed by these terms of use. By accessing and browsing this site you agree to be bound by these terms of use. We make this site available to you to in order to provide informat [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Terms {
            get {
                return ResourceManager.GetString("Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms.
        /// </summary>
        public static string termsTitle {
            get {
                return ResourceManager.GetString("termsTitle", resourceCulture);
            }
        }
    }
}
