//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Layout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Layout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Site.Resources.Layout", typeof(Layout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceling all orders....
        /// </summary>
        public static string blockCancelAllOrdersMessage {
            get {
                return ResourceManager.GetString("blockCancelAllOrdersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceling order....
        /// </summary>
        public static string blockCancelOrderMessage {
            get {
                return ResourceManager.GetString("blockCancelOrderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceling orders....
        /// </summary>
        public static string blockCancelTradePairMessage {
            get {
                return ResourceManager.GetString("blockCancelTradePairMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you ABSOLUTELY sure you want to cancel ALL your orders for ALL currencies?.
        /// </summary>
        public static string confirmCancelAllOrdersMessage {
            get {
                return ResourceManager.GetString("confirmCancelAllOrdersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel All Orders?.
        /// </summary>
        public static string confirmCancelAllOrdersTitle {
            get {
                return ResourceManager.GetString("confirmCancelAllOrdersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel All Orders?.
        /// </summary>
        public static string confirmCancelTradePairTitle {
            get {
                return ResourceManager.GetString("confirmCancelTradePairTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you ABSOLUTELY sure you want to cancel ALL orders in this list?.
        /// </summary>
        public static string confirmCancelTradePairTitleMessage {
            get {
                return ResourceManager.GetString("confirmCancelTradePairTitleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cryptopia Support.
        /// </summary>
        public static string errorContactSupportLink {
            get {
                return ResourceManager.GetString("errorContactSupportLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request, If problems persist please contact.
        /// </summary>
        public static string errorContactSupportText {
            get {
                return ResourceManager.GetString("errorContactSupportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh Snap!.
        /// </summary>
        public static string errorOhSnap {
            get {
                return ResourceManager.GetString("errorOhSnap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string errorTitle {
            get {
                return ResourceManager.GetString("errorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Page.
        /// </summary>
        public static string exportClipboardButton {
            get {
                return ResourceManager.GetString("exportClipboardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export page to csv.
        /// </summary>
        public static string exportCsvButton {
            get {
                return ResourceManager.GetString("exportCsvButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export page to Excel.
        /// </summary>
        public static string exportExcelButton {
            get {
                return ResourceManager.GetString("exportExcelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export page to pdf.
        /// </summary>
        public static string exportPdfButton {
            get {
                return ResourceManager.GetString("exportPdfButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Page.
        /// </summary>
        public static string exportPrintButton {
            get {
                return ResourceManager.GetString("exportPrintButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API.
        /// </summary>
        public static string footApi {
            get {
                return ResourceManager.GetString("footApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions.
        /// </summary>
        public static string footConditions {
            get {
                return ResourceManager.GetString("footConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string footContactUs {
            get {
                return ResourceManager.GetString("footContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string footCopyright {
            get {
                return ResourceManager.GetString("footCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Rights Reserved.
        /// </summary>
        public static string footCopyrightReserved {
            get {
                return ResourceManager.GetString("footCopyrightReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cryptopia IRC.
        /// </summary>
        public static string footCryptopiaIRC {
            get {
                return ResourceManager.GetString("footCryptopiaIRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help &amp; FAQ.
        /// </summary>
        public static string footHelpAndFaq {
            get {
                return ResourceManager.GetString("footHelpAndFaq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cryptopia Ltd. is not responsible for losses caused by outages, network volatility, wallet forks/maintenance or market conditions..
        /// </summary>
        public static string footNotResponsible {
            get {
                return ResourceManager.GetString("footNotResponsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private API.
        /// </summary>
        public static string footPrivateApi {
            get {
                return ResourceManager.GetString("footPrivateApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public API.
        /// </summary>
        public static string footPublicApi {
            get {
                return ResourceManager.GetString("footPublicApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string footSecurity {
            get {
                return ResourceManager.GetString("footSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social.
        /// </summary>
        public static string footSocial {
            get {
                return ResourceManager.GetString("footSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string footSupport {
            get {
                return ResourceManager.GetString("footSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage of Cryptopia.co.nz indicates acceptance of the Cryptopia Ltd..
        /// </summary>
        public static string footTerms {
            get {
                return ResourceManager.GetString("footTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions.
        /// </summary>
        public static string footTermsLink {
            get {
                return ResourceManager.GetString("footTermsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string footTextInformation {
            get {
                return ResourceManager.GetString("footTextInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already sent {0} good karma for this message..
        /// </summary>
        public static string karmaChatErrorAlreadySentMessage {
            get {
                return ResourceManager.GetString("karmaChatErrorAlreadySentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached your daily limit of 20 chat karma points..
        /// </summary>
        public static string karmaChatErrorLimitMessage {
            get {
                return ResourceManager.GetString("karmaChatErrorLimitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users message not found..
        /// </summary>
        public static string karmaChatErrorMessageNotFoundMessage {
            get {
                return ResourceManager.GetString("karmaChatErrorMessageNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully sent {0} good karma..
        /// </summary>
        public static string karmaChatIsSentMessage {
            get {
                return ResourceManager.GetString("karmaChatIsSentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1 Karma from {0} for your chat message..
        /// </summary>
        public static string karmaChatNotificationMessage {
            get {
                return ResourceManager.GetString("karmaChatNotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized..
        /// </summary>
        public static string karmaErrorUnauthorizedMessage {
            get {
                return ResourceManager.GetString("karmaErrorUnauthorizedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        public static string karmaErrorUserNotFoundMessage {
            get {
                return ResourceManager.GetString("karmaErrorUserNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already sent {0} good karma for this post..
        /// </summary>
        public static string karmaForumErrorAlreadySentMessage {
            get {
                return ResourceManager.GetString("karmaForumErrorAlreadySentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully sent {0} good karma..
        /// </summary>
        public static string karmaForumIsSentMessage {
            get {
                return ResourceManager.GetString("karmaForumIsSentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users message not found..
        /// </summary>
        public static string karmaForumMessageNotFoundMessage {
            get {
                return ResourceManager.GetString("karmaForumMessageNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1 Karma from {0} for your forum post..
        /// </summary>
        public static string karmaForumNotificationMessage {
            get {
                return ResourceManager.GetString("karmaForumNotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already sent {0} good karma for this tip..
        /// </summary>
        public static string karmaTipErrorAlreadySentMessage {
            get {
                return ResourceManager.GetString("karmaTipErrorAlreadySentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users tip not found..
        /// </summary>
        public static string karmaTipErrorNotFoundMessage {
            get {
                return ResourceManager.GetString("karmaTipErrorNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully sent {0} good karma..
        /// </summary>
        public static string karmaTipIsSentMessage {
            get {
                return ResourceManager.GetString("karmaTipIsSentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1 Karma from {0} for your tip..
        /// </summary>
        public static string karmaTipNotificationMessage {
            get {
                return ResourceManager.GetString("karmaTipNotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbidden Link.
        /// </summary>
        public static string linkifyForbiddenLink {
            get {
                return ResourceManager.GetString("linkifyForbiddenLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string menuAccount {
            get {
                return ResourceManager.GetString("menuAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbitrage.
        /// </summary>
        public static string menuArbitrage {
            get {
                return ResourceManager.GetString("menuArbitrage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balances.
        /// </summary>
        public static string menuBalances {
            get {
                return ResourceManager.GetString("menuBalances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Notifications.
        /// </summary>
        public static string menuClearNotifications {
            get {
                return ResourceManager.GetString("menuClearNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoinInfo.
        /// </summary>
        public static string menuCoinInfo {
            get {
                return ResourceManager.GetString("menuCoinInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Mode.
        /// </summary>
        public static string menuDayModeHint {
            get {
                return ResourceManager.GetString("menuDayModeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange.
        /// </summary>
        public static string menuExchange {
            get {
                return ResourceManager.GetString("menuExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forums.
        /// </summary>
        public static string menuForums {
            get {
                return ResourceManager.GetString("menuForums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string menuHistory {
            get {
                return ResourceManager.GetString("menuHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbox Messages.
        /// </summary>
        public static string menuInboxMessages {
            get {
                return ResourceManager.GetString("menuInboxMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string menuLogin {
            get {
                return ResourceManager.GetString("menuLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string menuLogoutHint {
            get {
                return ResourceManager.GetString("menuLogoutHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lotto.
        /// </summary>
        public static string menuLotto {
            get {
                return ResourceManager.GetString("menuLotto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketplace.
        /// </summary>
        public static string menuMarketplace {
            get {
                return ResourceManager.GetString("menuMarketplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markets.
        /// </summary>
        public static string menuMarkets {
            get {
                return ResourceManager.GetString("menuMarkets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string menuNews {
            get {
                return ResourceManager.GetString("menuNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night Mode.
        /// </summary>
        public static string menuNightModeHint {
            get {
                return ResourceManager.GetString("menuNightModeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new notifications.
        /// </summary>
        public static string menuNoNotification {
            get {
                return ResourceManager.GetString("menuNoNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string menuNotifications {
            get {
                return ResourceManager.GetString("menuNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Orders.
        /// </summary>
        public static string menuOpenOrders {
            get {
                return ResourceManager.GetString("menuOpenOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paytopia.
        /// </summary>
        public static string menuPaytopia {
            get {
                return ResourceManager.GetString("menuPaytopia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string menuRegister {
            get {
                return ResourceManager.GetString("menuRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewards.
        /// </summary>
        public static string menuRewards {
            get {
                return ResourceManager.GetString("menuRewards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        public static string menuSelectLanguageHint {
            get {
                return ResourceManager.GetString("menuSelectLanguageHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string menuSettings {
            get {
                return ResourceManager.GetString("menuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string menuSupport {
            get {
                return ResourceManager.GetString("menuSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallets.
        /// </summary>
        public static string menuWallets {
            get {
                return ResourceManager.GetString("menuWallets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        public static string menuWalletsDeposit {
            get {
                return ResourceManager.GetString("menuWalletsDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string menuWalletsTransfer {
            get {
                return ResourceManager.GetString("menuWalletsTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw.
        /// </summary>
        public static string menuWalletsWithdraw {
            get {
                return ResourceManager.GetString("menuWalletsWithdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please contact.
        /// </summary>
        public static string messageContactSupport {
            get {
                return ResourceManager.GetString("messageContactSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cryptopia Support.
        /// </summary>
        public static string messageContactSupportLink {
            get {
                return ResourceManager.GetString("messageContactSupportLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please.
        /// </summary>
        public static string messageLogin {
            get {
                return ResourceManager.GetString("messageLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to log in.
        /// </summary>
        public static string messageLoginEx {
            get {
                return ResourceManager.GetString("messageLoginEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here.
        /// </summary>
        public static string messageLoginLink {
            get {
                return ResourceManager.GetString("messageLoginLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crypto-Currency Trading, Forum and Marketplace platform..
        /// </summary>
        public static string metaDescription {
            get {
                return ResourceManager.GetString("metaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Request.
        /// </summary>
        public static string modalInvalidHeadline {
            get {
                return ResourceManager.GetString("modalInvalidHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request was not formed properly. Please refresh the page and try again..
        /// </summary>
        public static string modalInvalidInfoText {
            get {
                return ResourceManager.GetString("modalInvalidInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request was not formed properly. Please refresh the page and try again..
        /// </summary>
        public static string modalInvalidRequestMessage1 {
            get {
                return ResourceManager.GetString("modalInvalidRequestMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the problem continues, please contact support..
        /// </summary>
        public static string modalInvalidRequestMessage2 {
            get {
                return ResourceManager.GetString("modalInvalidRequestMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Request.
        /// </summary>
        public static string modalInvalidRequestTitle {
            get {
                return ResourceManager.GetString("modalInvalidRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the problem continues, please contact support..
        /// </summary>
        public static string modalInvalidSupportText {
            get {
                return ResourceManager.GetString("modalInvalidSupportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string modalLoadingMessage {
            get {
                return ResourceManager.GetString("modalLoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rated.
        /// </summary>
        public static string ratingRated {
            get {
                return ResourceManager.GetString("ratingRated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrated.
        /// </summary>
        public static string ratingUnrated {
            get {
                return ResourceManager.GetString("ratingUnrated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string starRatingHint {
            get {
                return ResourceManager.GetString("starRatingHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        public static string themeDark {
            get {
                return ResourceManager.GetString("themeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Mode.
        /// </summary>
        public static string themeLight {
            get {
                return ResourceManager.GetString("themeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized!.
        /// </summary>
        public static string unauthorizedHeadline {
            get {
                return ResourceManager.GetString("unauthorizedHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to be logged in to perform this action.
        /// </summary>
        public static string unauthorizedLoginMessage {
            get {
                return ResourceManager.GetString("unauthorizedLoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Login.
        /// </summary>
        public static string unauthorizedLoginMessageTitle {
            get {
                return ResourceManager.GetString("unauthorizedLoginMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to view this area..
        /// </summary>
        public static string unauthorizedMessage {
            get {
                return ResourceManager.GetString("unauthorizedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        public static string unauthorizedTitle {
            get {
                return ResourceManager.GetString("unauthorizedTitle", resourceCulture);
            }
        }
    }
}
