//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lotto {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lotto() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Site.Resources.Lotto", typeof(Lotto).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string createAmountLabel {
            get {
                return ResourceManager.GetString("createAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Balance.
        /// </summary>
        public static string createAvailableBalanceLabel {
            get {
                return ResourceManager.GetString("createAvailableBalanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Ticket.
        /// </summary>
        public static string createBuyTicketButton {
            get {
                return ResourceManager.GetString("createBuyTicketButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Lotto Ticket.
        /// </summary>
        public static string createHeadline {
            get {
                return ResourceManager.GetString("createHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy a ticket for the next {0} draw.
        /// </summary>
        public static string createText {
            get {
                return ResourceManager.GetString("createText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Price.
        /// </summary>
        public static string createTicketPriceLabel {
            get {
                return ResourceManager.GetString("createTicketPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        public static string createTotalPriceLabel {
            get {
                return ResourceManager.GetString("createTotalPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send email code to you two factor address, if problems persist please contact {0}.
        /// </summary>
        public static string createTwoFactorMailFailedMessage {
            get {
                return ResourceManager.GetString("createTwoFactorMailFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email successfully sent to your two factor address..
        /// </summary>
        public static string createTwoFactorMailSentMessage {
            get {
                return ResourceManager.GetString("createTwoFactorMailSentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending code....
        /// </summary>
        public static string createTwoFactorSendingMessage {
            get {
                return ResourceManager.GetString("createTwoFactorSendingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Ticket.
        /// </summary>
        public static string lottoBuyTicketButton {
            get {
                return ResourceManager.GetString("lottoBuyTicketButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully purchased {0} tickets for #{1}.
        /// </summary>
        public static string lottoCreateSuccessMessage {
            get {
                return ResourceManager.GetString("lottoCreateSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string lottoCreateTicketErrorTitle {
            get {
                return ResourceManager.GetString("lottoCreateTicketErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Two Factor code entered was incorrect or has expired, please try again..
        /// </summary>
        public static string lottoCreateTwoFactorErrorMessage {
            get {
                return ResourceManager.GetString("lottoCreateTwoFactorErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Fee.
        /// </summary>
        public static string lottoGameFeeLabel {
            get {
                return ResourceManager.GetString("lottoGameFeeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string lottoHistoryCurrencyColumn {
            get {
                return ResourceManager.GetString("lottoHistoryCurrencyColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw #.
        /// </summary>
        public static string lottoHistoryDrawColumn {
            get {
                return ResourceManager.GetString("lottoHistoryDrawColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Time.
        /// </summary>
        public static string lottoHistoryDrawTimeColumn {
            get {
                return ResourceManager.GetString("lottoHistoryDrawTimeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No lotto history found..
        /// </summary>
        public static string lottoHistoryEmptyListMessage {
            get {
                return ResourceManager.GetString("lottoHistoryEmptyListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lotto Prize History.
        /// </summary>
        public static string lottoHistoryHeadline {
            get {
                return ResourceManager.GetString("lottoHistoryHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lottoHistoryNameColumn {
            get {
                return ResourceManager.GetString("lottoHistoryNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        public static string lottoHistoryPlaceColumn {
            get {
                return ResourceManager.GetString("lottoHistoryPlaceColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prize.
        /// </summary>
        public static string lottoHistoryPrizeColumn {
            get {
                return ResourceManager.GetString("lottoHistoryPrizeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prize %.
        /// </summary>
        public static string lottoHistoryPrizePercentColumn {
            get {
                return ResourceManager.GetString("lottoHistoryPrizePercentColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string lottoHistoryTab {
            get {
                return ResourceManager.GetString("lottoHistoryTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket #.
        /// </summary>
        public static string lottoHistoryTicketColumn {
            get {
                return ResourceManager.GetString("lottoHistoryTicketColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total prize.
        /// </summary>
        public static string lottoHistoryTotalPrizeColumn {
            get {
                return ResourceManager.GetString("lottoHistoryTotalPrizeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string lottoHistoryUserColumn {
            get {
                return ResourceManager.GetString("lottoHistoryUserColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game: #{0}, Draw: #{1}.
        /// </summary>
        public static string lottoInfoText {
            get {
                return ResourceManager.GetString("lottoInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string lottoMyActiveCurrencyColumn {
            get {
                return ResourceManager.GetString("lottoMyActiveCurrencyColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw #.
        /// </summary>
        public static string lottoMyActiveDrawColumn {
            get {
                return ResourceManager.GetString("lottoMyActiveDrawColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no active tickets..
        /// </summary>
        public static string lottoMyActiveEmptyListMessage {
            get {
                return ResourceManager.GetString("lottoMyActiveEmptyListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Active Lotto tickets.
        /// </summary>
        public static string lottoMyActiveHeadline {
            get {
                return ResourceManager.GetString("lottoMyActiveHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lottoMyActiveNameColumn {
            get {
                return ResourceManager.GetString("lottoMyActiveNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Draw.
        /// </summary>
        public static string lottoMyActiveNextDrawColumn {
            get {
                return ResourceManager.GetString("lottoMyActiveNextDrawColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string lottoMyActivePriceColumn {
            get {
                return ResourceManager.GetString("lottoMyActivePriceColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket #.
        /// </summary>
        public static string lottoMyActiveTicketColumn {
            get {
                return ResourceManager.GetString("lottoMyActiveTicketColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        public static string lottoMyActiveTimestampColumn {
            get {
                return ResourceManager.GetString("lottoMyActiveTimestampColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Lotto.
        /// </summary>
        public static string lottoMyLottoTab {
            get {
                return ResourceManager.GetString("lottoMyLottoTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string lottoMyPrizeCurrencyColumn {
            get {
                return ResourceManager.GetString("lottoMyPrizeCurrencyColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw #.
        /// </summary>
        public static string lottoMyPrizeDrawColumn {
            get {
                return ResourceManager.GetString("lottoMyPrizeDrawColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Time.
        /// </summary>
        public static string lottoMyPrizeDrawTimeColumn {
            get {
                return ResourceManager.GetString("lottoMyPrizeDrawTimeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no lotto history..
        /// </summary>
        public static string lottoMyPrizeEmptyListMessage {
            get {
                return ResourceManager.GetString("lottoMyPrizeEmptyListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Lotto Prize History.
        /// </summary>
        public static string lottoMyPrizeHeadline {
            get {
                return ResourceManager.GetString("lottoMyPrizeHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lottoMyPrizeNameColumn {
            get {
                return ResourceManager.GetString("lottoMyPrizeNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        public static string lottoMyPrizePlaceColumn {
            get {
                return ResourceManager.GetString("lottoMyPrizePlaceColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prize.
        /// </summary>
        public static string lottoMyPrizePrizeColumn {
            get {
                return ResourceManager.GetString("lottoMyPrizePrizeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prize %.
        /// </summary>
        public static string lottoMyPrizePrizePercentColumn {
            get {
                return ResourceManager.GetString("lottoMyPrizePrizePercentColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket #.
        /// </summary>
        public static string lottoMyPrizeTicketColumn {
            get {
                return ResourceManager.GetString("lottoMyPrizeTicketColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total prize.
        /// </summary>
        public static string lottoMyPrizeTotalPrizeColumn {
            get {
                return ResourceManager.GetString("lottoMyPrizeTotalPrizeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Draw.
        /// </summary>
        public static string lottoNextDrawLabel {
            get {
                return ResourceManager.GetString("lottoNextDrawLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lotto.
        /// </summary>
        public static string lottoPageTitle {
            get {
                return ResourceManager.GetString("lottoPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prize.
        /// </summary>
        public static string lottoPrizeLabel {
            get {
                return ResourceManager.GetString("lottoPrizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lotto.
        /// </summary>
        public static string lottoTab {
            get {
                return ResourceManager.GetString("lottoTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Price.
        /// </summary>
        public static string lottoTicketPriceLabel {
            get {
                return ResourceManager.GetString("lottoTicketPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets In Draw.
        /// </summary>
        public static string lottoTicketsInDrawLabel {
            get {
                return ResourceManager.GetString("lottoTicketsInDrawLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email Code.
        /// </summary>
        public static string lottoTwoFactorMailSendButton {
            get {
                return ResourceManager.GetString("lottoTwoFactorMailSendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Tickets.
        /// </summary>
        public static string lottoYourTicketsLabel {
            get {
                return ResourceManager.GetString("lottoYourTicketsLabel", resourceCulture);
            }
        }
    }
}
