//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Paytopia {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Paytopia() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Site.Resources.Paytopia", typeof(Paytopia).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string currencyCurrencyLabel {
            get {
                return ResourceManager.GetString("currencyCurrencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &apos;Buy Now&apos; to purchase a new featured currency slot.
        /// </summary>
        public static string currencyInfoText {
            get {
                return ResourceManager.GetString("currencyInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next available featured slot for {0} is Week.
        /// </summary>
        public static string currencyNextAvailableWeekInfoText {
            get {
                return ResourceManager.GetString("currencyNextAvailableWeekInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending slots already purchased for.
        /// </summary>
        public static string currencyPurchasedInfoText {
            get {
                return ResourceManager.GetString("currencyPurchasedInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &apos;Buy Now&apos; to submit your coin, administrators will review the coin/code and begin the listing process immediately, if for any reason the listing is rejected due to incompatibility or the code review should fail the full listing price will be immediately refunded to your account..
        /// </summary>
        public static string exchangeComboBuyNowInfoText {
            get {
                return ResourceManager.GetString("exchangeComboBuyNowInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Combo Listing.
        /// </summary>
        public static string exchangeComboHeadline {
            get {
                return ResourceManager.GetString("exchangeComboHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Listing.
        /// </summary>
        public static string exchangeListingHeadline {
            get {
                return ResourceManager.GetString("exchangeListingHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &apos;Buy Now&apos; to submit your coin, administrators will review the coin/code and begin the listing process immediately, if for any reason the listing is rejected due to incompatibility or the code review should fail the full listing price will be immediately refunded to your account..
        /// </summary>
        public static string exchangeListingInfoText {
            get {
                return ResourceManager.GetString("exchangeListingInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &apos;Buy Now&apos; to purchase a new lotto slot, slot will remain active until {0}.
        /// </summary>
        public static string lottoBuyNowInfoText {
            get {
                return ResourceManager.GetString("lottoBuyNowInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Lotto Game.
        /// </summary>
        public static string lottoHeadline {
            get {
                return ResourceManager.GetString("lottoHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ultimate way to secure your account..
        /// </summary>
        public static string paytopiaAuthInfoText {
            get {
                return ResourceManager.GetString("paytopiaAuthInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Time Passwords.
        /// </summary>
        public static string paytopiaAuthLine1Text {
            get {
                return ResourceManager.GetString("paytopiaAuthLine1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worldwide Delivery.
        /// </summary>
        public static string paytopiaAuthLine2Text {
            get {
                return ResourceManager.GetString("paytopiaAuthLine2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Security.
        /// </summary>
        public static string paytopiaAuthLine3Text {
            get {
                return ResourceManager.GetString("paytopiaAuthLine3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive to Cryptopia.
        /// </summary>
        public static string paytopiaAuthLine4Text {
            get {
                return ResourceManager.GetString("paytopiaAuthLine4Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string paytopiaAvailableLabel {
            get {
                return ResourceManager.GetString("paytopiaAvailableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Now.
        /// </summary>
        public static string paytopiaBuyNowButton {
            get {
                return ResourceManager.GetString("paytopiaBuyNowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing subject to developer review.
        /// </summary>
        public static string paytopiaComboInfoText {
            get {
                return ResourceManager.GetString("paytopiaComboInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Listing.
        /// </summary>
        public static string paytopiaComboLine1Text {
            get {
                return ResourceManager.GetString("paytopiaComboLine1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Month Reward Slot.
        /// </summary>
        public static string paytopiaComboLine2Text {
            get {
                return ResourceManager.GetString("paytopiaComboLine2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Month Tipping Slot.
        /// </summary>
        public static string paytopiaComboLine3Text {
            get {
                return ResourceManager.GetString("paytopiaComboLine3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Month Featured Currency.
        /// </summary>
        public static string paytopiaComboLine4Text {
            get {
                return ResourceManager.GetString("paytopiaComboLine4Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEST&lt;br&gt;DEAL.
        /// </summary>
        public static string paytopiaComboStickerHtml {
            get {
                return ResourceManager.GetString("paytopiaComboStickerHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great advertising opportunity.
        /// </summary>
        public static string paytopiaCurrencyInfoText {
            get {
                return ResourceManager.GetString("paytopiaCurrencyInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 Weekly Slots.
        /// </summary>
        public static string paytopiaCurrencyLine1Text {
            get {
                return ResourceManager.GetString("paytopiaCurrencyLine1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Traffic Visibility.
        /// </summary>
        public static string paytopiaCurrencyLine2Text {
            get {
                return ResourceManager.GetString("paytopiaCurrencyLine2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing subject to developer review.
        /// </summary>
        public static string paytopiaExchangeInfoText {
            get {
                return ResourceManager.GetString("paytopiaExchangeInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Base Markets.
        /// </summary>
        public static string paytopiaExchangeLine1Text {
            get {
                return ResourceManager.GetString("paytopiaExchangeLine1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Performance Trade Engine.
        /// </summary>
        public static string paytopiaExchangeLine2Text {
            get {
                return ResourceManager.GetString("paytopiaExchangeLine2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbitrage Tools.
        /// </summary>
        public static string paytopiaExchangeLine3Text {
            get {
                return ResourceManager.GetString("paytopiaExchangeLine3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketplace Integration.
        /// </summary>
        public static string paytopiaExchangeLine4Text {
            get {
                return ResourceManager.GetString("paytopiaExchangeLine4Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Info.
        /// </summary>
        public static string paytopiaFaqLabel {
            get {
                return ResourceManager.GetString("paytopiaFaqLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cryptopia Authenticator FAQ.
        /// </summary>
        public static string paytopiaFaqLink {
            get {
                return ResourceManager.GetString("paytopiaFaqLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paytopia is a quick and easy place to purchase the features and services provided by Cryptopia.
        /// </summary>
        public static string paytopiaInfoText {
            get {
                return ResourceManager.GetString("paytopiaInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paytopia.
        /// </summary>
        public static string paytopiaPageTitle {
            get {
                return ResourceManager.GetString("paytopiaPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string paytopiaPriceLabel {
            get {
                return ResourceManager.GetString("paytopiaPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fantastic distribution mechanism.
        /// </summary>
        public static string paytopiaRewardInfoText {
            get {
                return ResourceManager.GetString("paytopiaRewardInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomized Payments.
        /// </summary>
        public static string paytopiaRewardLine1Text {
            get {
                return ResourceManager.GetString("paytopiaRewardLine1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faucet Style Distribution.
        /// </summary>
        public static string paytopiaRewardLine2Text {
            get {
                return ResourceManager.GetString("paytopiaRewardLine2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fantastic distribution mechanism.
        /// </summary>
        public static string paytopiaTippingInfoText {
            get {
                return ResourceManager.GetString("paytopiaTippingInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Support.
        /// </summary>
        public static string paytopiaTippingLine1Text {
            get {
                return ResourceManager.GetString("paytopiaTippingLine1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Tipping Options.
        /// </summary>
        public static string paytopiaTippingLine2Text {
            get {
                return ResourceManager.GetString("paytopiaTippingLine2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending slots already purchased for {0}.
        /// </summary>
        public static string poolAlreadyPurchasedInfoText {
            get {
                return ResourceManager.GetString("poolAlreadyPurchasedInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &apos;Buy Now&apos; to purchase a new featured pool slot.
        /// </summary>
        public static string poolBuyNowInfoText {
            get {
                return ResourceManager.GetString("poolBuyNowInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &apos;Buy Now&apos; to submit your coin, administrators will review the coin/code and begin the listing process immediately, if for any reason the listing is rejected due to incompatibility or the code review should fail the full listing price will be immediately refunded to your account..
        /// </summary>
        public static string poolListingBuyNowInfoText {
            get {
                return ResourceManager.GetString("poolListingBuyNowInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &apos;Buy Now&apos; to extend this pool subscription for another 30 days.
        /// </summary>
        public static string poolListingExtendInfoText {
            get {
                return ResourceManager.GetString("poolListingExtendInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoolListing.
        /// </summary>
        public static string poolListingHeadline {
            get {
                return ResourceManager.GetString("poolListingHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next available featured slot for {0} is Week.
        /// </summary>
        public static string poolNextAvailableInfoText {
            get {
                return ResourceManager.GetString("poolNextAvailableInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool.
        /// </summary>
        public static string poolPoolLabel {
            get {
                return ResourceManager.GetString("poolPoolLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &apos;Buy Now&apos; to purchase a new reward slot, slot will remain active until {0}.
        /// </summary>
        public static string rewardBuyNowInfoText {
            get {
                return ResourceManager.GetString("rewardBuyNowInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string rewardCurrencyLabel {
            get {
                return ResourceManager.GetString("rewardCurrencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string rewardExtendInfoLabel {
            get {
                return ResourceManager.GetString("rewardExtendInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This reward slot is still active, click &apos;Buy Now&apos; to extend this slot until {0}.
        /// </summary>
        public static string rewardExtendInfoText {
            get {
                return ResourceManager.GetString("rewardExtendInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Reward Slot.
        /// </summary>
        public static string rewardHeadline {
            get {
                return ResourceManager.GetString("rewardHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &apos;Buy Now&apos; to submit your share request, administrators will review your details and begin the share transfer process, if for any reason the request is rejected the full purchsae price will be immediately refunded to your account..
        /// </summary>
        public static string sharesBuyNowInfoText {
            get {
                return ResourceManager.GetString("sharesBuyNowInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure you have read and understand the {0} of owning a Cryptopia share..
        /// </summary>
        public static string sharesConditionsInfoText {
            get {
                return ResourceManager.GetString("sharesConditionsInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conditions.
        /// </summary>
        public static string sharesConditionsLink {
            get {
                return ResourceManager.GetString("sharesConditionsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cryptopia Shares.
        /// </summary>
        public static string sharesHeadline {
            get {
                return ResourceManager.GetString("sharesHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        public static string sharesTotalPriceLabel {
            get {
                return ResourceManager.GetString("sharesTotalPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &apos;Buy Now&apos; to purchase a new tipping slot, slot will remain active until {0}.
        /// </summary>
        public static string tipBuyNowInfoText {
            get {
                return ResourceManager.GetString("tipBuyNowInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string tipSlotCurrencyLabel {
            get {
                return ResourceManager.GetString("tipSlotCurrencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string tipSlotExtendInfoLabel {
            get {
                return ResourceManager.GetString("tipSlotExtendInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tipping slot is still active, click &apos;Buy Now&apos; to extend this slot until {0}.
        /// </summary>
        public static string tipSlotExtendInfoText {
            get {
                return ResourceManager.GetString("tipSlotExtendInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TipSlot.
        /// </summary>
        public static string tipSlotHeadline {
            get {
                return ResourceManager.GetString("tipSlotHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cryptopia Authentication Device.
        /// </summary>
        public static string twoFactorHeadline {
            get {
                return ResourceManager.GetString("twoFactorHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &apos;Buy Now&apos; to submit your Cryptopia Authentication device request, Your device will be sent out within 3 business days..
        /// </summary>
        public static string twoFactorInfoText {
            get {
                return ResourceManager.GetString("twoFactorInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string twoFactorMoreInfoLink {
            get {
                return ResourceManager.GetString("twoFactorMoreInfoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information on the Cryptopia Authentication device please see click {0}.
        /// </summary>
        public static string twoFactorMoreInfoText {
            get {
                return ResourceManager.GetString("twoFactorMoreInfoText", resourceCulture);
            }
        }
    }
}
