//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Reward {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Reward() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Site.Resources.Reward", typeof(Reward).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string rewardBalancesCurrencyColumn {
            get {
                return ResourceManager.GetString("rewardBalancesCurrencyColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string rewardBalancesDonateButton {
            get {
                return ResourceManager.GetString("rewardBalancesDonateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No balances avaliable..
        /// </summary>
        public static string rewardBalancesEmtpyListMessage {
            get {
                return ResourceManager.GetString("rewardBalancesEmtpyListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balances.
        /// </summary>
        public static string rewardBalancesHeadline {
            get {
                return ResourceManager.GetString("rewardBalancesHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining.
        /// </summary>
        public static string rewardBalancesRemainingColumn {
            get {
                return ResourceManager.GetString("rewardBalancesRemainingColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string rewardCurrencyColumn {
            get {
                return ResourceManager.GetString("rewardCurrencyColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rewards avaliable.
        /// </summary>
        public static string rewardEmptyListMessage {
            get {
                return ResourceManager.GetString("rewardEmptyListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewards.
        /// </summary>
        public static string rewardHeadline {
            get {
                return ResourceManager.GetString("rewardHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward History.
        /// </summary>
        public static string rewardHistoryHeadline {
            get {
                return ResourceManager.GetString("rewardHistoryHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward Information.
        /// </summary>
        public static string rewardInfoLink {
            get {
                return ResourceManager.GetString("rewardInfoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Cryptopia reward bot rewards you for using the site and can earn you coins for certain actions. Rewards occur for random coins with random amounts for random tasks during specific time windows, if the correct action is performed during the correct time then a reward is earned. You can currently recieve rewards for trading, inserting mining shares, finding blocks, tipping, voting and chatting. For more information on the rewardbot and how it works please visit the following thread {0}.
        /// </summary>
        public static string rewardInfoText {
            get {
                return ResourceManager.GetString("rewardInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24hr.
        /// </summary>
        public static string rewardLeaderboard24hrColumn {
            get {
                return ResourceManager.GetString("rewardLeaderboard24hrColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Time.
        /// </summary>
        public static string rewardLeaderboardAllTimeColumn {
            get {
                return ResourceManager.GetString("rewardLeaderboardAllTimeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No stats avaliable.
        /// </summary>
        public static string rewardLeaderboardEmptyListMessage {
            get {
                return ResourceManager.GetString("rewardLeaderboardEmptyListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaderboard.
        /// </summary>
        public static string rewardLeaderboardHeadline {
            get {
                return ResourceManager.GetString("rewardLeaderboardHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string rewardLeaderboardTypeColumn {
            get {
                return ResourceManager.GetString("rewardLeaderboardTypeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string rewardLeaderboardWeekColumn {
            get {
                return ResourceManager.GetString("rewardLeaderboardWeekColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewards.
        /// </summary>
        public static string rewardPageTitle {
            get {
                return ResourceManager.GetString("rewardPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward.
        /// </summary>
        public static string rewardRewardColumn {
            get {
                return ResourceManager.GetString("rewardRewardColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward %.
        /// </summary>
        public static string rewardRewardPercentageColumn {
            get {
                return ResourceManager.GetString("rewardRewardPercentageColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string rewardTimeColumn {
            get {
                return ResourceManager.GetString("rewardTimeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string rewardTypeColumn {
            get {
                return ResourceManager.GetString("rewardTypeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string rewardUserColumn {
            get {
                return ResourceManager.GetString("rewardUserColumn", resourceCulture);
            }
        }
    }
}
