//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Support {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Support() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Site.Resources.Support", typeof(Support).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitting....
        /// </summary>
        public static string createSubmitingMessage {
            get {
                return ResourceManager.GetString("createSubmitingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Support Ticket.
        /// </summary>
        public static string createTitle {
            get {
                return ResourceManager.GetString("createTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Reply.
        /// </summary>
        public static string replyTitle {
            get {
                return ResourceManager.GetString("replyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Request.
        /// </summary>
        public static string supportButton {
            get {
                return ResourceManager.GetString("supportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply Email.
        /// </summary>
        public static string supportEmailLabel {
            get {
                return ResourceManager.GetString("supportEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must supply a valid reply email address.
        /// </summary>
        public static string supportEmailRequiredError {
            get {
                return ResourceManager.GetString("supportEmailRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send email, please try again..
        /// </summary>
        public static string supportFailedError {
            get {
                return ResourceManager.GetString("supportFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string supportMessageLabel {
            get {
                return ResourceManager.GetString("supportMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must supply a message.
        /// </summary>
        public static string supportMessageRequiredError {
            get {
                return ResourceManager.GetString("supportMessageRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string supportPageTitle {
            get {
                return ResourceManager.GetString("supportPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid reCaptcha.
        /// </summary>
        public static string supportReCaptchaError {
            get {
                return ResourceManager.GetString("supportReCaptchaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending request....
        /// </summary>
        public static string supportSendingMessage {
            get {
                return ResourceManager.GetString("supportSendingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string supportSubjectLabel {
            get {
                return ResourceManager.GetString("supportSubjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must supply a message subject.
        /// </summary>
        public static string supportSubjectRequiredError {
            get {
                return ResourceManager.GetString("supportSubjectRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your support ticket was logged successfully..
        /// </summary>
        public static string supportSuccessMessage {
            get {
                return ResourceManager.GetString("supportSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;Having problems logging in, or have questions about the site?&lt;/h4&gt;
        ///					&lt;h4&gt;Send us a support request and one of our staff will be happy to assist.&lt;/h4&gt;.
        /// </summary>
        public static string supportSummaryHtml {
            get {
                return ResourceManager.GetString("supportSummaryHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support ticket #{ticketId} not found..
        /// </summary>
        public static string tickectNotFoundMessage {
            get {
                return ResourceManager.GetString("tickectNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found!.
        /// </summary>
        public static string tickectNotFoundMessageTitle {
            get {
                return ResourceManager.GetString("tickectNotFoundMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting admin reply..
        /// </summary>
        public static string ticketAwaitingStatus {
            get {
                return ResourceManager.GetString("ticketAwaitingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category:.
        /// </summary>
        public static string ticketCategoryLabel {
            get {
                return ResourceManager.GetString("ticketCategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Ticket.
        /// </summary>
        public static string ticketCloseButton {
            get {
                return ResourceManager.GetString("ticketCloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string ticketClosedLabel {
            get {
                return ResourceManager.GetString("ticketClosedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string ticketClosedStatus {
            get {
                return ResourceManager.GetString("ticketClosedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close support ticket #{0}?.
        /// </summary>
        public static string ticketCloseQuestion {
            get {
                return ResourceManager.GetString("ticketCloseQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close support ticket?.
        /// </summary>
        public static string ticketCloseQuestionTitle {
            get {
                return ResourceManager.GetString("ticketCloseQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing ticket....
        /// </summary>
        public static string ticketClosingMessage {
            get {
                return ResourceManager.GetString("ticketClosingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket description.
        /// </summary>
        public static string ticketDescriptionLabel {
            get {
                return ResourceManager.GetString("ticketDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket History.
        /// </summary>
        public static string ticketHistoryLabel {
            get {
                return ResourceManager.GetString("ticketHistoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Information:.
        /// </summary>
        public static string ticketInfoHeadline {
            get {
                return ResourceManager.GetString("ticketInfoHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string ticketNewStatus {
            get {
                return ResourceManager.GetString("ticketNewStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened.
        /// </summary>
        public static string ticketOpenedLabel {
            get {
                return ResourceManager.GetString("ticketOpenedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string ticketPageTitle {
            get {
                return ResourceManager.GetString("ticketPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin replied..
        /// </summary>
        public static string ticketRepliedStatus {
            get {
                return ResourceManager.GetString("ticketRepliedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply Ticket.
        /// </summary>
        public static string ticketReplyButton {
            get {
                return ResourceManager.GetString("ticketReplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return To Support.
        /// </summary>
        public static string ticketReturnButton {
            get {
                return ResourceManager.GetString("ticketReturnButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        public static string ticketSenderLabel {
            get {
                return ResourceManager.GetString("ticketSenderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string ticketStatusLabel {
            get {
                return ResourceManager.GetString("ticketStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Update.
        /// </summary>
        public static string ticketUpdatedLabel {
            get {
                return ResourceManager.GetString("ticketUpdatedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Ticket.
        /// </summary>
        public static string ticketViewButton {
            get {
                return ResourceManager.GetString("ticketViewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no closed support tickets..
        /// </summary>
        public static string userClosedTicketsEmptyListMessage {
            get {
                return ResourceManager.GetString("userClosedTicketsEmptyListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed Support Tickets.
        /// </summary>
        public static string userClosedTicketsHeadline {
            get {
                return ResourceManager.GetString("userClosedTicketsHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Ticket.
        /// </summary>
        public static string userCreateTicketButton {
            get {
                return ResourceManager.GetString("userCreateTicketButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no open support tickets..
        /// </summary>
        public static string userOpenTicketsEmptyListMessage {
            get {
                return ResourceManager.GetString("userOpenTicketsEmptyListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Support Tickets.
        /// </summary>
        public static string userOpenTicketsHeadline {
            get {
                return ResourceManager.GetString("userOpenTicketsHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Support And Communications.
        /// </summary>
        public static string userPageTitle {
            get {
                return ResourceManager.GetString("userPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Having problems? Want to contact the team? Create a support ticket and one of our staff will be happy to assist..
        /// </summary>
        public static string userSummaryText {
            get {
                return ResourceManager.GetString("userSummaryText", resourceCulture);
            }
        }
    }
}
