//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Site.Resources.UserData", typeof(UserData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string balancesActionsColumn {
            get {
                return ResourceManager.GetString("balancesActionsColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string balancesAvailableColumn {
            get {
                return ResourceManager.GetString("balancesAvailableColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string balancesAvailableHintLabel {
            get {
                return ResourceManager.GetString("balancesAvailableHintLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string balancesCurrencyColumn {
            get {
                return ResourceManager.GetString("balancesCurrencyColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have used {0} of your {1} NZD.
        /// </summary>
        public static string balancesDailyLimitMessage {
            get {
                return ResourceManager.GetString("balancesDailyLimitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to daily limit.
        /// </summary>
        public static string balancesDailyLimitMessageLink {
            get {
                return ResourceManager.GetString("balancesDailyLimitMessageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        public static string balancesDepositButtonHint {
            get {
                return ResourceManager.GetString("balancesDepositButtonHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Balance Details.
        /// </summary>
        public static string balancesDetailsHint {
            get {
                return ResourceManager.GetString("balancesDetailsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dust {0} Balance.
        /// </summary>
        public static string balancesDustButtonHint {
            get {
                return ResourceManager.GetString("balancesDustButtonHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you ABSOLUTELY sure you want to discard your {0} balance?, this is NOT reversible!!.
        /// </summary>
        public static string balancesDustQuestion {
            get {
                return ResourceManager.GetString("balancesDustQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dust Balance.
        /// </summary>
        public static string balancesDustQuestionTitle {
            get {
                return ResourceManager.GetString("balancesDustQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No balances found..
        /// </summary>
        public static string balancesEmptyListMessage {
            get {
                return ResourceManager.GetString("balancesEmptyListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est. BTC.
        /// </summary>
        public static string balancesEstBtcColumn {
            get {
                return ResourceManager.GetString("balancesEstBtcColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Altcoin only).
        /// </summary>
        public static string balancesEstimatedAltcoinSufixLabel {
            get {
                return ResourceManager.GetString("balancesEstimatedAltcoinSufixLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated BTC.
        /// </summary>
        public static string balancesEstimatedBtcHintLabel {
            get {
                return ResourceManager.GetString("balancesEstimatedBtcHintLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated BTC.
        /// </summary>
        public static string balancesEstimatedLabel {
            get {
                return ResourceManager.GetString("balancesEstimatedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        public static string balancesFavoriteColumn {
            get {
                return ResourceManager.GetString("balancesFavoriteColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites only.
        /// </summary>
        public static string balancesFavoritesOnlyLabel {
            get {
                return ResourceManager.GetString("balancesFavoritesOnlyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balances.
        /// </summary>
        public static string balancesHeadline {
            get {
                return ResourceManager.GetString("balancesHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Held For Orders.
        /// </summary>
        public static string balancesHeldForOrdersHintLabel {
            get {
                return ResourceManager.GetString("balancesHeldForOrdersHintLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide zero balances.
        /// </summary>
        public static string balancesHideZeroBalancesLabel {
            get {
                return ResourceManager.GetString("balancesHideZeroBalancesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Orders.
        /// </summary>
        public static string balancesOpenOrdersColumn {
            get {
                return ResourceManager.GetString("balancesOpenOrdersColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Withdraw.
        /// </summary>
        public static string balancesPendingWithdrawHintLabel {
            get {
                return ResourceManager.GetString("balancesPendingWithdrawHintLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string balancesSearchLabel {
            get {
                return ResourceManager.GetString("balancesSearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string balancesStatusHintLabel {
            get {
                return ResourceManager.GetString("balancesStatusHintLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string balancesTotalColumn {
            get {
                return ResourceManager.GetString("balancesTotalColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string balancesTotalHintLabel {
            get {
                return ResourceManager.GetString("balancesTotalHintLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string balancesTransferButtonHint {
            get {
                return ResourceManager.GetString("balancesTransferButtonHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unconfirmed.
        /// </summary>
        public static string balancesUnconfirmedHintLabel {
            get {
                return ResourceManager.GetString("balancesUnconfirmedHintLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING.
        /// </summary>
        public static string balancesWarningLabel {
            get {
                return ResourceManager.GetString("balancesWarningLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please do not mine directly to your Cryptopia addresses, We do not support generated transactions from pools like P2Pool etc..
        /// </summary>
        public static string balancesWarningMessage {
            get {
                return ResourceManager.GetString("balancesWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw.
        /// </summary>
        public static string balancesWithdrawButtonHint {
            get {
                return ResourceManager.GetString("balancesWithdrawButtonHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no deposits..
        /// </summary>
        public static string depositHisotryEmptyListMessage {
            get {
                return ResourceManager.GetString("depositHisotryEmptyListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string depositHistoryAmountColumn {
            get {
                return ResourceManager.GetString("depositHistoryAmountColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conf..
        /// </summary>
        public static string depositHistoryConfColumn {
            get {
                return ResourceManager.GetString("depositHistoryConfColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string depositHistoryCurrencyColumn {
            get {
                return ResourceManager.GetString("depositHistoryCurrencyColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit History.
        /// </summary>
        public static string depositHistoryHeadline {
            get {
                return ResourceManager.GetString("depositHistoryHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string depositHistoryStatusColumn {
            get {
                return ResourceManager.GetString("depositHistoryStatusColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        public static string depositHistoryTimestampColumn {
            get {
                return ResourceManager.GetString("depositHistoryTimestampColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        public static string depositHistoryTransactionColumn {
            get {
                return ResourceManager.GetString("depositHistoryTransactionColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string depositHistoryTypeColumn {
            get {
                return ResourceManager.GetString("depositHistoryTypeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string karmaAmountColumn {
            get {
                return ResourceManager.GetString("karmaAmountColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no karma..
        /// </summary>
        public static string karmaEmptyListMessage {
            get {
                return ResourceManager.GetString("karmaEmptyListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string karmaFromColumn {
            get {
                return ResourceManager.GetString("karmaFromColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karma.
        /// </summary>
        public static string karmaHeadline {
            get {
                return ResourceManager.GetString("karmaHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no karma history..
        /// </summary>
        public static string karmaHistoryEmptyListMessage {
            get {
                return ResourceManager.GetString("karmaHistoryEmptyListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karma History.
        /// </summary>
        public static string karmaHistoryHeadline {
            get {
                return ResourceManager.GetString("karmaHistoryHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karma points.
        /// </summary>
        public static string karmaPointsLabel {
            get {
                return ResourceManager.GetString("karmaPointsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karma Received.
        /// </summary>
        public static string karmaReceivedHeadline {
            get {
                return ResourceManager.GetString("karmaReceivedHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        public static string karmaTimestampColumn {
            get {
                return ResourceManager.GetString("karmaTimestampColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string karmaTotalLabel {
            get {
                return ResourceManager.GetString("karmaTotalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Info.
        /// </summary>
        public static string karmaTransactionInfoColumn {
            get {
                return ResourceManager.GetString("karmaTransactionInfoColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string karmaTypeColumn {
            get {
                return ResourceManager.GetString("karmaTypeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspent.
        /// </summary>
        public static string karmaUnspentLabel {
            get {
                return ResourceManager.GetString("karmaUnspentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buyer.
        /// </summary>
        public static string marketBuyerColumn {
            get {
                return ResourceManager.GetString("marketBuyerColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buyers Feedback.
        /// </summary>
        public static string marketBuyersFeedbackColumn {
            get {
                return ResourceManager.GetString("marketBuyersFeedbackColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceling item....
        /// </summary>
        public static string marketCancelingMessage {
            get {
                return ResourceManager.GetString("marketCancelingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Listing.
        /// </summary>
        public static string marketCancelListingButton {
            get {
                return ResourceManager.GetString("marketCancelListingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel this market listing?.
        /// </summary>
        public static string marketCancelListingQuestion {
            get {
                return ResourceManager.GetString("marketCancelListingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Listing?.
        /// </summary>
        public static string marketCancelListingQuestionTitle {
            get {
                return ResourceManager.GetString("marketCancelListingQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string marketClosedColumn {
            get {
                return ResourceManager.GetString("marketClosedColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes.
        /// </summary>
        public static string marketClosesColumn {
            get {
                return ResourceManager.GetString("marketClosesColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Listing.
        /// </summary>
        public static string marketEditListingButton {
            get {
                return ResourceManager.GetString("marketEditListingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No open market listings..
        /// </summary>
        public static string marketEmptyListMessage {
            get {
                return ResourceManager.GetString("marketEmptyListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketplace Items.
        /// </summary>
        public static string marketHeadline {
            get {
                return ResourceManager.GetString("marketHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no market history.
        /// </summary>
        public static string marketHistoryEmptyListMessage {
            get {
                return ResourceManager.GetString("marketHistoryEmptyListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketplace History.
        /// </summary>
        public static string marketHistoryHeadline {
            get {
                return ResourceManager.GetString("marketHistoryHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to listing.
        /// </summary>
        public static string marketOpenButton {
            get {
                return ResourceManager.GetString("marketOpenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened.
        /// </summary>
        public static string marketOpenedColumn {
            get {
                return ResourceManager.GetString("marketOpenedColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller.
        /// </summary>
        public static string marketSellerColumn {
            get {
                return ResourceManager.GetString("marketSellerColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sellers feedback.
        /// </summary>
        public static string marketSellersFeedbackColumn {
            get {
                return ResourceManager.GetString("marketSellersFeedbackColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string marketStatusColumn {
            get {
                return ResourceManager.GetString("marketStatusColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string marketTitleColumn {
            get {
                return ResourceManager.GetString("marketTitleColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string marketTypeColumn {
            get {
                return ResourceManager.GetString("marketTypeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string messageFromLabel {
            get {
                return ResourceManager.GetString("messageFromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Message.
        /// </summary>
        public static string messagesCreateHeadline {
            get {
                return ResourceManager.GetString("messagesCreateHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All.
        /// </summary>
        public static string messagesDeleteAllButton {
            get {
                return ResourceManager.GetString("messagesDeleteAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All.
        /// </summary>
        public static string messagesDeleteAllButtonHint {
            get {
                return ResourceManager.GetString("messagesDeleteAllButtonHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete ALL Inbox messages?.
        /// </summary>
        public static string messagesDeleteAllInboxQuestion {
            get {
                return ResourceManager.GetString("messagesDeleteAllInboxQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Inbox.
        /// </summary>
        public static string messagesDeleteAllInboxQuestionTitle {
            get {
                return ResourceManager.GetString("messagesDeleteAllInboxQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete ALL Outbox messages?.
        /// </summary>
        public static string messagesDeleteAllOutboxQuestion {
            get {
                return ResourceManager.GetString("messagesDeleteAllOutboxQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Outbox.
        /// </summary>
        public static string messagesDeleteAllOutboxQuestionTitle {
            get {
                return ResourceManager.GetString("messagesDeleteAllOutboxQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string messagesDeleteButton {
            get {
                return ResourceManager.GetString("messagesDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string messagesDeleteButtonHint {
            get {
                return ResourceManager.GetString("messagesDeleteButtonHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected message?.
        /// </summary>
        public static string messagesDeleteQuestion {
            get {
                return ResourceManager.GetString("messagesDeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Message.
        /// </summary>
        public static string messagesDeleteQuestionTitle {
            get {
                return ResourceManager.GetString("messagesDeleteQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string messagesHeadline {
            get {
                return ResourceManager.GetString("messagesHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no inbox messages..
        /// </summary>
        public static string messagesInboxEmptyListMessage {
            get {
                return ResourceManager.GetString("messagesInboxEmptyListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbox.
        /// </summary>
        public static string messagesInboxHeadline {
            get {
                return ResourceManager.GetString("messagesInboxHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbox.
        /// </summary>
        public static string messagesInboxTab {
            get {
                return ResourceManager.GetString("messagesInboxTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Inbox.
        /// </summary>
        public static string messagesInboxTabSearchPlaceholder {
            get {
                return ResourceManager.GetString("messagesInboxTabSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just now.
        /// </summary>
        public static string messagesJustNowLabel {
            get {
                return ResourceManager.GetString("messagesJustNowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string messagesMessageLabel {
            get {
                return ResourceManager.GetString("messagesMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string messagesNewButton {
            get {
                return ResourceManager.GetString("messagesNewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New message.
        /// </summary>
        public static string messagesNewButtonHint {
            get {
                return ResourceManager.GetString("messagesNewButtonHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no outbox messages..
        /// </summary>
        public static string messagesOutboxEmptyListMessage {
            get {
                return ResourceManager.GetString("messagesOutboxEmptyListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outbox.
        /// </summary>
        public static string messagesOutboxTab {
            get {
                return ResourceManager.GetString("messagesOutboxTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Outbox.
        /// </summary>
        public static string messagesOutboxTabSearchPlaceholder {
            get {
                return ResourceManager.GetString("messagesOutboxTabSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to example: Lorde;Frodo;Sheep;Pavlova.
        /// </summary>
        public static string messagesRecipiantsExampleInfoText {
            get {
                return ResourceManager.GetString("messagesRecipiantsExampleInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can send messages to multiple recipients by separating the usernames with &apos;;&apos;,.
        /// </summary>
        public static string messagesRecipiantsInfoText {
            get {
                return ResourceManager.GetString("messagesRecipiantsInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipiants.
        /// </summary>
        public static string messagesRecipiantsLabel {
            get {
                return ResourceManager.GetString("messagesRecipiantsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        public static string messagesReplyButton {
            get {
                return ResourceManager.GetString("messagesReplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply to message.
        /// </summary>
        public static string messagesReplyButtonHint {
            get {
                return ResourceManager.GetString("messagesReplyButtonHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply To {0}!.
        /// </summary>
        public static string messagesReplyToHeadline {
            get {
                return ResourceManager.GetString("messagesReplyToHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string messagesReportButton {
            get {
                return ResourceManager.GetString("messagesReportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report message.
        /// </summary>
        public static string messagesReportButtonHint {
            get {
                return ResourceManager.GetString("messagesReportButtonHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string messagesReportCommentLabel {
            get {
                return ResourceManager.GetString("messagesReportCommentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Message.
        /// </summary>
        public static string messagesReportHeadline {
            get {
                return ResourceManager.GetString("messagesReportHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string messagesReportReasonLabel {
            get {
                return ResourceManager.GetString("messagesReportReasonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string messagesSubjectLabel {
            get {
                return ResourceManager.GetString("messagesSubjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;Warning!&lt;/h4&gt;
        ///				&lt;p&gt;Beware of imposters, Cryptopia staff do &lt;b&gt;NOT&lt;/b&gt; provide updates, special offers or downloads in Inbox messages.  Official News and Information are only ever posted on our &lt;a href=&quot;/News&quot; target=&quot;_blank&quot;&gt;News Page&lt;/a&gt;, &lt;a href=&quot;https://twitter.com/Cryptopia_NZ&quot; target=&quot;_blank&quot;&gt;Twitter&lt;/a&gt;, &lt;a href=&quot;https://www.facebook.com/cryptopiaexchange&quot; target=&quot;_blank&quot;&gt;Facebook&lt;/a&gt; and &lt;a href=&quot;/Forums&quot; target=&quot;_blank&quot;&gt;Forums&lt;/a&gt;.&lt;br /&gt;Please ask in our &lt;a href=&quot;https://discord.gg/2kMgEgw&quot; t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string messagesWarningHtml {
            get {
                return ResourceManager.GetString("messagesWarningHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string messageToLabel {
            get {
                return ResourceManager.GetString("messageToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string mineshaftHistoryAmountColumn {
            get {
                return ResourceManager.GetString("mineshaftHistoryAmountColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block Height.
        /// </summary>
        public static string mineshaftHistoryBlockHeightColumn {
            get {
                return ResourceManager.GetString("mineshaftHistoryBlockHeightColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no mining payments..
        /// </summary>
        public static string mineshaftHistoryEmptyListMessage {
            get {
                return ResourceManager.GetString("mineshaftHistoryEmptyListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mineshaft History.
        /// </summary>
        public static string mineshaftHistoryHeadline {
            get {
                return ResourceManager.GetString("mineshaftHistoryHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool.
        /// </summary>
        public static string mineshaftHistoryPoolColumn {
            get {
                return ResourceManager.GetString("mineshaftHistoryPoolColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shares.
        /// </summary>
        public static string mineshaftHistorySharesColumn {
            get {
                return ResourceManager.GetString("mineshaftHistorySharesColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string mineshaftHistoryStatusColumn {
            get {
                return ResourceManager.GetString("mineshaftHistoryStatusColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        public static string mineshaftHistoryTimestampColumn {
            get {
                return ResourceManager.GetString("mineshaftHistoryTimestampColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer #.
        /// </summary>
        public static string mineshaftHistoryTransferColumn {
            get {
                return ResourceManager.GetString("mineshaftHistoryTransferColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string mineshaftHistoryTransferPendingValue {
            get {
                return ResourceManager.GetString("mineshaftHistoryTransferPendingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All.
        /// </summary>
        public static string notificationsDeleteAllButton {
            get {
                return ResourceManager.GetString("notificationsDeleteAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting....
        /// </summary>
        public static string notificationsDeletingMessage {
            get {
                return ResourceManager.GetString("notificationsDeletingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss All.
        /// </summary>
        public static string notificationsDismissAllButton {
            get {
                return ResourceManager.GetString("notificationsDismissAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no notifications..
        /// </summary>
        public static string notificationsEmptyListInfoText {
            get {
                return ResourceManager.GetString("notificationsEmptyListInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new notifications..
        /// </summary>
        public static string notificationsEmptyNewListInfoText {
            get {
                return ResourceManager.GetString("notificationsEmptyNewListInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string notificationsHeadline {
            get {
                return ResourceManager.GetString("notificationsHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 1000 notifications.
        /// </summary>
        public static string notificationsList1000InfoText {
            get {
                return ResourceManager.GetString("notificationsList1000InfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 100 notifications.
        /// </summary>
        public static string notificationsList100InfoText {
            get {
                return ResourceManager.GetString("notificationsList100InfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark all as read.
        /// </summary>
        public static string notificationsMarkAllAsReadButton {
            get {
                return ResourceManager.GetString("notificationsMarkAllAsReadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string paytopiaAmountColumn {
            get {
                return ResourceManager.GetString("paytopiaAmountColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begins.
        /// </summary>
        public static string paytopiaBeginsColumn {
            get {
                return ResourceManager.GetString("paytopiaBeginsColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coin.
        /// </summary>
        public static string paytopiaCoinColumn {
            get {
                return ResourceManager.GetString("paytopiaCoinColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you have no payments..
        /// </summary>
        public static string paytopiaEmptyListMessage {
            get {
                return ResourceManager.GetString("paytopiaEmptyListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends.
        /// </summary>
        public static string paytopiaEndsColumn {
            get {
                return ResourceManager.GetString("paytopiaEndsColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paytopia Payments.
        /// </summary>
        public static string paytopiaHeadline {
            get {
                return ResourceManager.GetString("paytopiaHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string paytopiaIdColumn {
            get {
                return ResourceManager.GetString("paytopiaIdColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string paytopiaInfoButton {
            get {
                return ResourceManager.GetString("paytopiaInfoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsAnon..
        /// </summary>
        public static string paytopiaIsAnonColumn {
            get {
                return ResourceManager.GetString("paytopiaIsAnonColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefundId.
        /// </summary>
        public static string paytopiaRefundIdColumn {
            get {
                return ResourceManager.GetString("paytopiaRefundIdColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string paytopiaRefundIdErrorValue {
            get {
                return ResourceManager.GetString("paytopiaRefundIdErrorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string paytopiaStatusColumn {
            get {
                return ResourceManager.GetString("paytopiaStatusColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        public static string paytopiaTimestampColumn {
            get {
                return ResourceManager.GetString("paytopiaTimestampColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransferId.
        /// </summary>
        public static string paytopiaTransferIdColumn {
            get {
                return ResourceManager.GetString("paytopiaTransferIdColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string paytopiaTransferIdErrorValue {
            get {
                return ResourceManager.GetString("paytopiaTransferIdErrorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string paytopiaTransferIdPendingValue {
            get {
                return ResourceManager.GetString("paytopiaTransferIdPendingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string paytopiaTypeColumn {
            get {
                return ResourceManager.GetString("paytopiaTypeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string paytopiaUserNameColumn {
            get {
                return ResourceManager.GetString("paytopiaUserNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no referral history..
        /// </summary>
        public static string referralHistoryEmptyListMessage {
            get {
                return ResourceManager.GetString("referralHistoryEmptyListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referral History.
        /// </summary>
        public static string referralHistoryHeadline {
            get {
                return ResourceManager.GetString("referralHistoryHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastUpdate.
        /// </summary>
        public static string referralHistoryLastUpdateColumn {
            get {
                return ResourceManager.GetString("referralHistoryLastUpdateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefCount.
        /// </summary>
        public static string referralHistoryRefCountColumn {
            get {
                return ResourceManager.GetString("referralHistoryRefCountColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoundId.
        /// </summary>
        public static string referralHistoryRoundIdColumn {
            get {
                return ResourceManager.GetString("referralHistoryRoundIdColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string referralHistoryStatusColumn {
            get {
                return ResourceManager.GetString("referralHistoryStatusColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TradeFeeAmount.
        /// </summary>
        public static string referralHistoryTradeFeeAmountColumn {
            get {
                return ResourceManager.GetString("referralHistoryTradeFeeAmountColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransferId.
        /// </summary>
        public static string referralHistoryTransferIdColumn {
            get {
                return ResourceManager.GetString("referralHistoryTransferIdColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string shareholderCurrencyColumn {
            get {
                return ResourceManager.GetString("shareholderCurrencyColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dividend Calculation.
        /// </summary>
        public static string shareholderDividendCalculationLabel {
            get {
                return ResourceManager.GetString("shareholderDividendCalculationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ((Fees - Expenses) / TotalShares) * ShareCount.
        /// </summary>
        public static string shareholderDividendCalculationText {
            get {
                return ResourceManager.GetString("shareholderDividendCalculationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        public static string shareholderExpensesColumn {
            get {
                return ResourceManager.GetString("shareholderExpensesColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee Income.
        /// </summary>
        public static string shareholderFeeIncomeColumn {
            get {
                return ResourceManager.GetString("shareholderFeeIncomeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shareholder.
        /// </summary>
        public static string shareholderHeadline {
            get {
                return ResourceManager.GetString("shareholderHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Information.
        /// </summary>
        public static string shareholderInfoHeadline {
            get {
                return ResourceManager.GetString("shareholderInfoHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Information.
        /// </summary>
        public static string shareholderPaymentHeadline {
            get {
                return ResourceManager.GetString("shareholderPaymentHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string shareholderPayoutHistoryAmountColumn {
            get {
                return ResourceManager.GetString("shareholderPayoutHistoryAmountColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string shareholderPayoutHistoryCurrencyColumn {
            get {
                return ResourceManager.GetString("shareholderPayoutHistoryCurrencyColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payout History.
        /// </summary>
        public static string shareholderPayoutHistoryHeadline {
            get {
                return ResourceManager.GetString("shareholderPayoutHistoryHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string shareholderPayoutHistoryIdColumn {
            get {
                return ResourceManager.GetString("shareholderPayoutHistoryIdColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        public static string shareholderPayoutHistoryTimestampColumn {
            get {
                return ResourceManager.GetString("shareholderPayoutHistoryTimestampColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payout Period.
        /// </summary>
        public static string shareholderPayoutPeriodColumn {
            get {
                return ResourceManager.GetString("shareholderPayoutPeriodColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no payouts..
        /// </summary>
        public static string shareholderPayoutsEmptyListMessage {
            get {
                return ResourceManager.GetString("shareholderPayoutsEmptyListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ((Income - Expenses) / TotalShares) * ShareCount.
        /// </summary>
        public static string shareholderPaytopiaDividendCalculationText {
            get {
                return ResourceManager.GetString("shareholderPaytopiaDividendCalculationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paytopia Dividends.
        /// </summary>
        public static string shareholderPaytopiaDividendsHeadline {
            get {
                return ResourceManager.GetString("shareholderPaytopiaDividendsHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string shareholderPaytopiaHistoryAmountColumn {
            get {
                return ResourceManager.GetString("shareholderPaytopiaHistoryAmountColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string shareholderPaytopiaHistoryCurrencyColumn {
            get {
                return ResourceManager.GetString("shareholderPaytopiaHistoryCurrencyColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrencyId.
        /// </summary>
        public static string shareholderPaytopiaHistoryCurrencyIdColumn {
            get {
                return ResourceManager.GetString("shareholderPaytopiaHistoryCurrencyIdColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paytopia History.
        /// </summary>
        public static string shareholderPaytopiaHistoryHeadline {
            get {
                return ResourceManager.GetString("shareholderPaytopiaHistoryHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string shareholderPaytopiaHistoryIdColumn {
            get {
                return ResourceManager.GetString("shareholderPaytopiaHistoryIdColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Type.
        /// </summary>
        public static string shareholderPaytopiaHistoryItemTypeColumn {
            get {
                return ResourceManager.GetString("shareholderPaytopiaHistoryItemTypeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        public static string shareholderPaytopiaHistorySymbolColumn {
            get {
                return ResourceManager.GetString("shareholderPaytopiaHistorySymbolColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        public static string shareholderPaytopiaHistoryTimestampColumn {
            get {
                return ResourceManager.GetString("shareholderPaytopiaHistoryTimestampColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per Share.
        /// </summary>
        public static string shareholderPerShareColumn {
            get {
                return ResourceManager.GetString("shareholderPerShareColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share %.
        /// </summary>
        public static string shareholderSharePercentColumn {
            get {
                return ResourceManager.GetString("shareholderSharePercentColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shares.
        /// </summary>
        public static string shareholderSharesColumn {
            get {
                return ResourceManager.GetString("shareholderSharesColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string shareholderSiteExpensesDescriptionColumn {
            get {
                return ResourceManager.GetString("shareholderSiteExpensesDescriptionColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Expenses.
        /// </summary>
        public static string shareholderSiteExpensesHeadline {
            get {
                return ResourceManager.GetString("shareholderSiteExpensesHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price (BTC).
        /// </summary>
        public static string shareholderSiteExpensesPriceBtcColumn {
            get {
                return ResourceManager.GetString("shareholderSiteExpensesPriceBtcColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price ($USD).
        /// </summary>
        public static string shareholderSiteExpensesPriceUsdColumn {
            get {
                return ResourceManager.GetString("shareholderSiteExpensesPriceUsdColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string shareholderSiteExpensesTotalLabel {
            get {
                return ResourceManager.GetString("shareholderSiteExpensesTotalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlgoType.
        /// </summary>
        public static string shareholderSubmissionAlgoTypeLabel {
            get {
                return ResourceManager.GetString("shareholderSubmissionAlgoTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlockExplorer.
        /// </summary>
        public static string shareholderSubmissionBlockExplorerLabel {
            get {
                return ResourceManager.GetString("shareholderSubmissionBlockExplorerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExtraInfo.
        /// </summary>
        public static string shareholderSubmissionExtraInfoLabel {
            get {
                return ResourceManager.GetString("shareholderSubmissionExtraInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission.
        /// </summary>
        public static string shareholderSubmissionHeadline {
            get {
                return ResourceManager.GetString("shareholderSubmissionHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LaunchForum.
        /// </summary>
        public static string shareholderSubmissionLaunchForumLabel {
            get {
                return ResourceManager.GetString("shareholderSubmissionLaunchForumLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string shareholderSubmissionNameLabel {
            get {
                return ResourceManager.GetString("shareholderSubmissionNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetworkType.
        /// </summary>
        public static string shareholderSubmissionNetworkTypeLabel {
            get {
                return ResourceManager.GetString("shareholderSubmissionNetworkTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool.
        /// </summary>
        public static string shareholderSubmissionPoolLabel {
            get {
                return ResourceManager.GetString("shareholderSubmissionPoolLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string shareholderSubmissionSourceLabel {
            get {
                return ResourceManager.GetString("shareholderSubmissionSourceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        public static string shareholderSubmissionSymbolLabel {
            get {
                return ResourceManager.GetString("shareholderSubmissionSymbolLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string shareholderSubmissionTypeLabel {
            get {
                return ResourceManager.GetString("shareholderSubmissionTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string shareholderSubmissionWebsiteLabel {
            get {
                return ResourceManager.GetString("shareholderSubmissionWebsiteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithm.
        /// </summary>
        public static string shareholderSubmitionAlgorithmLabel {
            get {
                return ResourceManager.GetString("shareholderSubmitionAlgorithmLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period Begins.
        /// </summary>
        public static string shareholderSubmitionPeriodBeginsLabel {
            get {
                return ResourceManager.GetString("shareholderSubmitionPeriodBeginsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period Ends.
        /// </summary>
        public static string shareholderSubmitionPeriodEndsLabel {
            get {
                return ResourceManager.GetString("shareholderSubmitionPeriodEndsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string shareholderSuspendedDetailLink {
            get {
                return ResourceManager.GetString("shareholderSuspendedDetailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more details, join us on in the Shareholders channel on Discord by clicking {0}.
        /// </summary>
        public static string shareholderSuspendedDetailsText {
            get {
                return ResourceManager.GetString("shareholderSuspendedDetailsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page has been suspended pending the Shareholder&apos;s General Meeting where a new Shareholder Agreement will be voted on..
        /// </summary>
        public static string shareholderSuspendedText {
            get {
                return ResourceManager.GetString("shareholderSuspendedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Shares.
        /// </summary>
        public static string shareholderTotalSharesColumn {
            get {
                return ResourceManager.GetString("shareholderTotalSharesColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Dividends.
        /// </summary>
        public static string shareholderTradeDividendsHeadline {
            get {
                return ResourceManager.GetString("shareholderTradeDividendsHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Dividends.
        /// </summary>
        public static string shareholderYourDividendsColumn {
            get {
                return ResourceManager.GetString("shareholderYourDividendsColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        public static string sharehoulderSubmissionTypeExtensionValue {
            get {
                return ResourceManager.GetString("sharehoulderSubmissionTypeExtensionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string termDepositsClosedColumn {
            get {
                return ResourceManager.GetString("termDepositsClosedColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no closed term deposits..
        /// </summary>
        public static string termDepositsClosedEmptyListMessage {
            get {
                return ResourceManager.GetString("termDepositsClosedEmptyListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed Term Deposits.
        /// </summary>
        public static string termDepositsClosedHeadline {
            get {
                return ResourceManager.GetString("termDepositsClosedHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All open term deposits have now been closed and the FULL term interest has been paid, we do apologize for the inconvenience this may have caused.
        /// </summary>
        public static string termDepositsDot2infoText {
            get {
                return ResourceManager.GetString("termDepositsDot2infoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to regulatory complications we are no longer able to provide Dotcoin(DOT) term deposits.
        /// </summary>
        public static string termDepositsDotInfoText {
            get {
                return ResourceManager.GetString("termDepositsDotInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term Deposits.
        /// </summary>
        public static string termDepositsHeadline {
            get {
                return ResourceManager.GetString("termDepositsHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string termDepositsIdColumn {
            get {
                return ResourceManager.GetString("termDepositsIdColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InterestRate.
        /// </summary>
        public static string termDepositsInterestRateColumn {
            get {
                return ResourceManager.GetString("termDepositsInterestRateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment.
        /// </summary>
        public static string termDepositsInvestmentColumn {
            get {
                return ResourceManager.GetString("termDepositsInvestmentColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string termDepositsPaymentColumn {
            get {
                return ResourceManager.GetString("termDepositsPaymentColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no term deposit payments..
        /// </summary>
        public static string termDepositsPaymentEmptyListMessage {
            get {
                return ResourceManager.GetString("termDepositsPaymentEmptyListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term Deposit Payments.
        /// </summary>
        public static string termDepositsPaymentsHeadline {
            get {
                return ResourceManager.GetString("termDepositsPaymentsHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        public static string termDepositsStartedColumn {
            get {
                return ResourceManager.GetString("termDepositsStartedColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string termDepositsStatusColumn {
            get {
                return ResourceManager.GetString("termDepositsStatusColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term.
        /// </summary>
        public static string termDepositsTermColumn {
            get {
                return ResourceManager.GetString("termDepositsTermColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TermDepositId.
        /// </summary>
        public static string termDepositsTermDepositIdColumn {
            get {
                return ResourceManager.GetString("termDepositsTermDepositIdColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        public static string termDepositsTimestampColumn {
            get {
                return ResourceManager.GetString("termDepositsTimestampColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransactionId.
        /// </summary>
        public static string termDepositsTransactionIdColumn {
            get {
                return ResourceManager.GetString("termDepositsTransactionIdColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string termDepositsTypeColumn {
            get {
                return ResourceManager.GetString("termDepositsTypeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WithdrawId.
        /// </summary>
        public static string termDepositsWithdrawIdColumn {
            get {
                return ResourceManager.GetString("termDepositsWithdrawIdColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string tradesAmountColumn {
            get {
                return ResourceManager.GetString("tradesAmountColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel All.
        /// </summary>
        public static string tradesCancelAllButton {
            get {
                return ResourceManager.GetString("tradesCancelAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No open orders..
        /// </summary>
        public static string tradesEmptyListMessage {
            get {
                return ResourceManager.GetString("tradesEmptyListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee.
        /// </summary>
        public static string tradesFeeColumn {
            get {
                return ResourceManager.GetString("tradesFeeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Orders.
        /// </summary>
        public static string tradesHeadline {
            get {
                return ResourceManager.GetString("tradesHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no trade history..
        /// </summary>
        public static string tradesHistoryEmptyListMessage {
            get {
                return ResourceManager.GetString("tradesHistoryEmptyListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade History.
        /// </summary>
        public static string tradesHistoryHeadline {
            get {
                return ResourceManager.GetString("tradesHistoryHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market.
        /// </summary>
        public static string tradesMarketColumn {
            get {
                return ResourceManager.GetString("tradesMarketColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string tradesRateColumn {
            get {
                return ResourceManager.GetString("tradesRateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining.
        /// </summary>
        public static string tradesRemainingColumn {
            get {
                return ResourceManager.GetString("tradesRemainingColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        public static string tradesTimestampColumn {
            get {
                return ResourceManager.GetString("tradesTimestampColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string tradesTotalColumn {
            get {
                return ResourceManager.GetString("tradesTotalColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TradePairId.
        /// </summary>
        public static string tradesTradePairIdColumn {
            get {
                return ResourceManager.GetString("tradesTradePairIdColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string tradesTypeColumn {
            get {
                return ResourceManager.GetString("tradesTypeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string transferAmountColumn {
            get {
                return ResourceManager.GetString("transferAmountColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string transferCurrencyColumn {
            get {
                return ResourceManager.GetString("transferCurrencyColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no transfers..
        /// </summary>
        public static string transferEmptyListMessage {
            get {
                return ResourceManager.GetString("transferEmptyListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee.
        /// </summary>
        public static string transferFeeColumn {
            get {
                return ResourceManager.GetString("transferFeeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer History.
        /// </summary>
        public static string transferHeadline {
            get {
                return ResourceManager.GetString("transferHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver.
        /// </summary>
        public static string transferReceiverColumn {
            get {
                return ResourceManager.GetString("transferReceiverColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        public static string transferSenderColumn {
            get {
                return ResourceManager.GetString("transferSenderColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        public static string transferTimestampColumn {
            get {
                return ResourceManager.GetString("transferTimestampColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string transferTypeColumn {
            get {
                return ResourceManager.GetString("transferTypeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string withdrawAddressColumn {
            get {
                return ResourceManager.GetString("withdrawAddressColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string withdrawAmountColumn {
            get {
                return ResourceManager.GetString("withdrawAmountColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Failed.
        /// </summary>
        public static string withdrawCancelErrorMessageTitle {
            get {
                return ResourceManager.GetString("withdrawCancelErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceling....
        /// </summary>
        public static string withdrawCancelingMessage {
            get {
                return ResourceManager.GetString("withdrawCancelingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel this withdrawal?.
        /// </summary>
        public static string withdrawCancelQuestion {
            get {
                return ResourceManager.GetString("withdrawCancelQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Withdrawal?.
        /// </summary>
        public static string withdrawCancelQuestionTitle {
            get {
                return ResourceManager.GetString("withdrawCancelQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw Canceled!.
        /// </summary>
        public static string withdrawCancelSuccessMessageTitle {
            get {
                return ResourceManager.GetString("withdrawCancelSuccessMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string withdrawCurrencyColumn {
            get {
                return ResourceManager.GetString("withdrawCurrencyColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no withdrawals..
        /// </summary>
        public static string withdrawEmptyListMessage {
            get {
                return ResourceManager.GetString("withdrawEmptyListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee.
        /// </summary>
        public static string withdrawFeeColumn {
            get {
                return ResourceManager.GetString("withdrawFeeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw History.
        /// </summary>
        public static string withdrawHeadline {
            get {
                return ResourceManager.GetString("withdrawHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend Email.
        /// </summary>
        public static string withdrawResendEmailButton {
            get {
                return ResourceManager.GetString("withdrawResendEmailButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Error!.
        /// </summary>
        public static string withdrawResendEmailErrorMessageTitle {
            get {
                return ResourceManager.GetString("withdrawResendEmailErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to resend this withdrawal&apos;s email confirmation?.
        /// </summary>
        public static string withdrawResendEmailQuestion {
            get {
                return ResourceManager.GetString("withdrawResendEmailQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend Email Confirmation?.
        /// </summary>
        public static string withdrawResendEmailQuestionTitle {
            get {
                return ResourceManager.GetString("withdrawResendEmailQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Sent.
        /// </summary>
        public static string withdrawResendEmailSuccessMessageTitle {
            get {
                return ResourceManager.GetString("withdrawResendEmailSuccessMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending confimation....
        /// </summary>
        public static string withdrawResendingEmailMessage {
            get {
                return ResourceManager.GetString("withdrawResendingEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string withdrawStatusColumn {
            get {
                return ResourceManager.GetString("withdrawStatusColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        public static string withdrawTimestampColumn {
            get {
                return ResourceManager.GetString("withdrawTimestampColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransactionId.
        /// </summary>
        public static string withdrawTransactionIdColumn {
            get {
                return ResourceManager.GetString("withdrawTransactionIdColumn", resourceCulture);
            }
        }
    }
}
