//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class User {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal User() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Site.Resources.User", typeof(User).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Avatar.
        /// </summary>
        public static string avatarHeadline {
            get {
                return ResourceManager.GetString("avatarHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended image size is 60x60 pixels, Images larger will be resized to fit..
        /// </summary>
        public static string avatarInfoText {
            get {
                return ResourceManager.GetString("avatarInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offensive or obscene images may be removed by Cryptopia moderators..
        /// </summary>
        public static string avatarWarningText {
            get {
                return ResourceManager.GetString("avatarWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string menuAccountLabel {
            get {
                return ResourceManager.GetString("menuAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balances.
        /// </summary>
        public static string menuBalancesLabel {
            get {
                return ResourceManager.GetString("menuBalancesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit History.
        /// </summary>
        public static string menuDepositHistoryLabel {
            get {
                return ResourceManager.GetString("menuDepositHistoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karma.
        /// </summary>
        public static string menuKarmaLabel {
            get {
                return ResourceManager.GetString("menuKarmaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karma Points.
        /// </summary>
        public static string menuKarmaPointsLabel {
            get {
                return ResourceManager.GetString("menuKarmaPointsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Items.
        /// </summary>
        public static string menuMarketItemsLabel {
            get {
                return ResourceManager.GetString("menuMarketItemsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketplace History.
        /// </summary>
        public static string menuMarketplaceHistoryLabel {
            get {
                return ResourceManager.GetString("menuMarketplaceHistoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string menuMessagesLabel {
            get {
                return ResourceManager.GetString("menuMessagesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mineshaft History.
        /// </summary>
        public static string menuMineshaftHistoryLabel {
            get {
                return ResourceManager.GetString("menuMineshaftHistoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string menuNotificationsLabel {
            get {
                return ResourceManager.GetString("menuNotificationsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Trades.
        /// </summary>
        public static string menuOpenTradesLabel {
            get {
                return ResourceManager.GetString("menuOpenTradesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string menuPageTitle {
            get {
                return ResourceManager.GetString("menuPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paytopia.
        /// </summary>
        public static string menuPaytopiaLabel {
            get {
                return ResourceManager.GetString("menuPaytopiaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referral History.
        /// </summary>
        public static string menuReferralHistoryLabel {
            get {
                return ResourceManager.GetString("menuReferralHistoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string menuSecurityLabel {
            get {
                return ResourceManager.GetString("menuSecurityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string menuSettingsLabel {
            get {
                return ResourceManager.GetString("menuSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shareholder.
        /// </summary>
        public static string menuShareholderLabel {
            get {
                return ResourceManager.GetString("menuShareholderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term Deposits.
        /// </summary>
        public static string menuTermDepositsLabel {
            get {
                return ResourceManager.GetString("menuTermDepositsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade History.
        /// </summary>
        public static string menuTradeHistoryLabel {
            get {
                return ResourceManager.GetString("menuTradeHistoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer History.
        /// </summary>
        public static string menuTransferHistoryLabel {
            get {
                return ResourceManager.GetString("menuTransferHistoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trust Rating.
        /// </summary>
        public static string menuTrustRatingLabel {
            get {
                return ResourceManager.GetString("menuTrustRatingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw History.
        /// </summary>
        public static string menuWithdrawHistoryLabel {
            get {
                return ResourceManager.GetString("menuWithdrawHistoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Details.
        /// </summary>
        public static string prifileDetailsHeadline {
            get {
                return ResourceManager.GetString("prifileDetailsHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to account.
        /// </summary>
        public static string profileAvatarErrorLink {
            get {
                return ResourceManager.GetString("profileAvatarErrorLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Creating Avatar.
        /// </summary>
        public static string profileAvatarErrorTitle {
            get {
                return ResourceManager.GetString("profileAvatarErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar.
        /// </summary>
        public static string profileAvatarLabel {
            get {
                return ResourceManager.GetString("profileAvatarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to security reasons your main email address cannot be changed here, If you need to change your email please contact Cryptopia Support..
        /// </summary>
        public static string profileCannotChangeEmailMessage {
            get {
                return ResourceManager.GetString("profileCannotChangeEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Email Info..
        /// </summary>
        public static string profileCannotChangeEmailMessageTitle {
            get {
                return ResourceManager.GetString("profileCannotChangeEmailMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Avatar.
        /// </summary>
        public static string profileChangeAvatarButton {
            get {
                return ResourceManager.GetString("profileChangeAvatarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Avatar Image.
        /// </summary>
        public static string profileChangeAvatarHint {
            get {
                return ResourceManager.GetString("profileChangeAvatarHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string profileHeadline {
            get {
                return ResourceManager.GetString("profileHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referral Count.
        /// </summary>
        public static string profileReferralCountLabel {
            get {
                return ResourceManager.GetString("profileReferralCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referral Details.
        /// </summary>
        public static string profileReferralHeadline {
            get {
                return ResourceManager.GetString("profileReferralHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View referral history.
        /// </summary>
        public static string profileReferralHistoryLink {
            get {
                return ResourceManager.GetString("profileReferralHistoryLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Referral Link.
        /// </summary>
        public static string profileReferralLinkNotificationTitle {
            get {
                return ResourceManager.GetString("profileReferralLinkNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referred By.
        /// </summary>
        public static string profileReferralReferredByLabel {
            get {
                return ResourceManager.GetString("profileReferralReferredByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Cryptopia referral system rewards users for referring customers to the site, for each referred user you will receive {0}% of that users trade fees converted to DOT Please provide the link below to the user you like, if he registers an account using your link you will start being rewarded for their activity..
        /// </summary>
        public static string profileReferralText {
            get {
                return ResourceManager.GetString("profileReferralText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Fees Bonus.
        /// </summary>
        public static string profileReferralTradeFeesBonusLabel {
            get {
                return ResourceManager.GetString("profileReferralTradeFeesBonusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string profileSaveButton {
            get {
                return ResourceManager.GetString("profileSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Security.
        /// </summary>
        public static string securityAccountHeadline {
            get {
                return ResourceManager.GetString("securityAccountHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddressBook Withdraw Only.
        /// </summary>
        public static string securityAccountWithdrawAddressBookLabel {
            get {
                return ResourceManager.GetString("securityAccountWithdrawAddressBookLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Withdraw Email Confirmation.
        /// </summary>
        public static string securityAccountWithdrawDisableEmailLabel {
            get {
                return ResourceManager.GetString("securityAccountWithdrawDisableEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw Settings.
        /// </summary>
        public static string securityAccountWithdrawHeadline {
            get {
                return ResourceManager.GetString("securityAccountWithdrawHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string securityAddressBookAddNewButton {
            get {
                return ResourceManager.GetString("securityAddressBookAddNewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string securityAddressBookAddressColumn {
            get {
                return ResourceManager.GetString("securityAddressBookAddressColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string securityAddressBookCreateAddressLabel {
            get {
                return ResourceManager.GetString("securityAddressBookCreateAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account Number.
        /// </summary>
        public static string securityAddressBookCreateBankAccountNumberLabel {
            get {
                return ResourceManager.GetString("securityAddressBookCreateBankAccountNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        public static string securityAddressBookCreateBankReferenceLabel {
            get {
                return ResourceManager.GetString("securityAddressBookCreateBankReferenceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string securityAddressBookCreateButton {
            get {
                return ResourceManager.GetString("securityAddressBookCreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrencyId.
        /// </summary>
        public static string securityAddressBookCreateCurrencyIdLabel {
            get {
                return ResourceManager.GetString("securityAddressBookCreateCurrencyIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Address Book Entry.
        /// </summary>
        public static string securityAddressBookCreateHeadline {
            get {
                return ResourceManager.GetString("securityAddressBookCreateHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string securityAddressBookCreateLabelLabel {
            get {
                return ResourceManager.GetString("securityAddressBookCreateLabelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentId.
        /// </summary>
        public static string securityAddressBookCreatePaymentIdLabel {
            get {
                return ResourceManager.GetString("securityAddressBookCreatePaymentIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waves Token Address.
        /// </summary>
        public static string securityAddressBookCreateWavesLabel {
            get {
                return ResourceManager.GetString("securityAddressBookCreateWavesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternatively you can save your WAVES token address..
        /// </summary>
        public static string securityAddressBookCreateWavesMessage {
            get {
                return ResourceManager.GetString("securityAddressBookCreateWavesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string securityAddressBookCurrencyColumn {
            get {
                return ResourceManager.GetString("securityAddressBookCurrencyColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrencyId.
        /// </summary>
        public static string securityAddressBookCurrencyIdColumn {
            get {
                return ResourceManager.GetString("securityAddressBookCurrencyIdColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete address book entry.
        /// </summary>
        public static string securityAddressBookDeleteHint {
            get {
                return ResourceManager.GetString("securityAddressBookDeleteHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this address book item?.
        /// </summary>
        public static string securityAddressBookDeleteQuestionMessage {
            get {
                return ResourceManager.GetString("securityAddressBookDeleteQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Address?.
        /// </summary>
        public static string securityAddressBookDeleteQuestionTitle {
            get {
                return ResourceManager.GetString("securityAddressBookDeleteQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no addresses saved..
        /// </summary>
        public static string securityAddressBookEmptyListMessage {
            get {
                return ResourceManager.GetString("securityAddressBookEmptyListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw Address Book.
        /// </summary>
        public static string securityAddressBookHeadline {
            get {
                return ResourceManager.GetString("securityAddressBookHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string securityAddressBookIdColumn {
            get {
                return ResourceManager.GetString("securityAddressBookIdColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string securityAddressBookLabelColumn {
            get {
                return ResourceManager.GetString("securityAddressBookLabelColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string securityAddressBookTypeColumn {
            get {
                return ResourceManager.GetString("securityAddressBookTypeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable API.
        /// </summary>
        public static string securityApiEnableLabel {
            get {
                return ResourceManager.GetString("securityApiEnableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow withdraw to any address via the API, otherwise limited to Addreessbook entires.
        /// </summary>
        public static string securityApiEnableUnsafeWithdrawalHint {
            get {
                return ResourceManager.GetString("securityApiEnableUnsafeWithdrawalHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow unsafe withdraw.
        /// </summary>
        public static string securityApiEnableUnsafeWithdrawalLabel {
            get {
                return ResourceManager.GetString("securityApiEnableUnsafeWithdrawalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Not reccomended).
        /// </summary>
        public static string securityApiEnableUnsafeWithdrawalWarningLabel {
            get {
                return ResourceManager.GetString("securityApiEnableUnsafeWithdrawalWarningLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Withdrawal.
        /// </summary>
        public static string securityApiEnableWithdrawalLabel {
            get {
                return ResourceManager.GetString("securityApiEnableWithdrawalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate API key, if problem persists please contact {0}..
        /// </summary>
        public static string securityApiGenerationFailedLinkMessage {
            get {
                return ResourceManager.GetString("securityApiGenerationFailedLinkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate API key, if problem persists please contact Cryptopia Support..
        /// </summary>
        public static string securityApiGenerationFailedMessage {
            get {
                return ResourceManager.GetString("securityApiGenerationFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Settings.
        /// </summary>
        public static string securityApiHeadline {
            get {
                return ResourceManager.GetString("securityApiHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Key.
        /// </summary>
        public static string securityApiNewKeyButton {
            get {
                return ResourceManager.GetString("securityApiNewKeyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string securityApiSaveButton {
            get {
                return ResourceManager.GetString("securityApiSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string securityPasswordConfirmLabel {
            get {
                return ResourceManager.GetString("securityPasswordConfirmLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string securityPasswordHeadline {
            get {
                return ResourceManager.GetString("securityPasswordHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string securityPasswordNewLabel {
            get {
                return ResourceManager.GetString("securityPasswordNewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string securityPasswordOldLabel {
            get {
                return ResourceManager.GetString("securityPasswordOldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string securityPasswordSaveButton {
            get {
                return ResourceManager.GetString("securityPasswordSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated password..
        /// </summary>
        public static string securityPasswordUpdatedMessage {
            get {
                return ResourceManager.GetString("securityPasswordUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation email can only be disabled if withdraw TFA is enabled..
        /// </summary>
        public static string securityTfaEmailErrorMessage {
            get {
                return ResourceManager.GetString("securityTfaEmailErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Factor Security.
        /// </summary>
        public static string securityTwoFactorHeadline {
            get {
                return ResourceManager.GetString("securityTwoFactorHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer is required.
        /// </summary>
        public static string securityUnlockAnswerRequiredError {
            get {
                return ResourceManager.GetString("securityUnlockAnswerRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock.
        /// </summary>
        public static string securityUnlockButton {
            get {
                return ResourceManager.GetString("securityUnlockButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cryptopia Code.
        /// </summary>
        public static string securityUnlockCryptopiaCodeLabel {
            get {
                return ResourceManager.GetString("securityUnlockCryptopiaCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your Cryptopia Authenticator code..
        /// </summary>
        public static string securityUnlockCryptopiaCodeMessage {
            get {
                return ResourceManager.GetString("securityUnlockCryptopiaCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cryptopia Auth. code is required.
        /// </summary>
        public static string securityUnlockCryptopiaRequiredError {
            get {
                return ResourceManager.GetString("securityUnlockCryptopiaRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your unlock code has been sent to your registered two factor email address.
        /// </summary>
        public static string securityUnlockEmailCodeIsSentMessage {
            get {
                return ResourceManager.GetString("securityUnlockEmailCodeIsSentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Code.
        /// </summary>
        public static string securityUnlockEmailCodeLabel {
            get {
                return ResourceManager.GetString("securityUnlockEmailCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the code sent to your email address..
        /// </summary>
        public static string securityUnlockEmailCodeMessage {
            get {
                return ResourceManager.GetString("securityUnlockEmailCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured sending twofactor code email, If problems persists please contact {0}.
        /// </summary>
        public static string securityUnlockEmailCodeNotSentError {
            get {
                return ResourceManager.GetString("securityUnlockEmailCodeNotSentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Send Failed!.
        /// </summary>
        public static string securityUnlockEmailCodeNotSentErrorTitle {
            get {
                return ResourceManager.GetString("securityUnlockEmailCodeNotSentErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Code.
        /// </summary>
        public static string securityUnlockGoogleCodeLabel {
            get {
                return ResourceManager.GetString("securityUnlockGoogleCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your Google Authenticator code..
        /// </summary>
        public static string securityUnlockGoogleCodeMessage {
            get {
                return ResourceManager.GetString("securityUnlockGoogleCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Auth. code is required.
        /// </summary>
        public static string securityUnlockGoogleCodeRequiredError {
            get {
                return ResourceManager.GetString("securityUnlockGoogleCodeRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Settings.
        /// </summary>
        public static string securityUnlockHeadline {
            get {
                return ResourceManager.GetString("securityUnlockHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid two factor..
        /// </summary>
        public static string securityUnlockInvalidCodeError {
            get {
                return ResourceManager.GetString("securityUnlockInvalidCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string securityUnlockPasswordLabel {
            get {
                return ResourceManager.GetString("securityUnlockPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your site password..
        /// </summary>
        public static string securityUnlockPasswordMessage {
            get {
                return ResourceManager.GetString("securityUnlockPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string securityUnlockPasswordRequiredError {
            get {
                return ResourceManager.GetString("securityUnlockPasswordRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question 1.
        /// </summary>
        public static string securityUnlockQuestion1Label {
            get {
                return ResourceManager.GetString("securityUnlockQuestion1Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question 2.
        /// </summary>
        public static string securityUnlockQuestion2Label {
            get {
                return ResourceManager.GetString("securityUnlockQuestion2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please answer your security questions..
        /// </summary>
        public static string securityUnlockQuestionsMessage {
            get {
                return ResourceManager.GetString("securityUnlockQuestionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Token Expired..
        /// </summary>
        public static string securityUnlockTokenExpiredError {
            get {
                return ResourceManager.GetString("securityUnlockTokenExpiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your two factor pin code..
        /// </summary>
        public static string securityUnlockTwoFactorCodeMessage {
            get {
                return ResourceManager.GetString("securityUnlockTwoFactorCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Code.
        /// </summary>
        public static string securityUnlockTwoFactorLabel {
            get {
                return ResourceManager.GetString("securityUnlockTwoFactorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PinCode is required.
        /// </summary>
        public static string securityUnlockTwoFactorRequiredError {
            get {
                return ResourceManager.GetString("securityUnlockTwoFactorRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Emoticons.
        /// </summary>
        public static string settingsChatDisableEmoticonsLabel {
            get {
                return ResourceManager.GetString("settingsChatDisableEmoticonsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Tipping.
        /// </summary>
        public static string settingsChatDisableTippingLabel {
            get {
                return ResourceManager.GetString("settingsChatDisableTippingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat ignore List.
        /// </summary>
        public static string settingsChatIgnoreHeadline {
            get {
                return ResourceManager.GetString("settingsChatIgnoreHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User to un/ignore.
        /// </summary>
        public static string settingsChatIgnoreLabel {
            get {
                return ResourceManager.GetString("settingsChatIgnoreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Settings.
        /// </summary>
        public static string settingsChatSettingsHeadline {
            get {
                return ResourceManager.GetString("settingsChatSettingsHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Logon Email.
        /// </summary>
        public static string settingsDisableLogonEmailLabel {
            get {
                return ResourceManager.GetString("settingsDisableLogonEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Karma Notifications.
        /// </summary>
        public static string settingsNotificationDisableKarmaLabel {
            get {
                return ResourceManager.GetString("settingsNotificationDisableKarmaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Marketplace Notifications.
        /// </summary>
        public static string settingsNotificationDisableMarketplaceLabel {
            get {
                return ResourceManager.GetString("settingsNotificationDisableMarketplaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Mineshaft Notifications.
        /// </summary>
        public static string settingsNotificationDisableMineshaftLabel {
            get {
                return ResourceManager.GetString("settingsNotificationDisableMineshaftLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Reward Notifications.
        /// </summary>
        public static string settingsNotificationDisableRewardLabel {
            get {
                return ResourceManager.GetString("settingsNotificationDisableRewardLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Tip Notifications.
        /// </summary>
        public static string settingsNotificationDisableTipLabel {
            get {
                return ResourceManager.GetString("settingsNotificationDisableTipLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Settings.
        /// </summary>
        public static string settingsNotificationHeadline {
            get {
                return ResourceManager.GetString("settingsNotificationHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Settings.
        /// </summary>
        public static string settingsOtherSettingsHeadline {
            get {
                return ResourceManager.GetString("settingsOtherSettingsHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Site Rewards.
        /// </summary>
        public static string settingsRewardsDisableLable {
            get {
                return ResourceManager.GetString("settingsRewardsDisableLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Rewards.
        /// </summary>
        public static string settingsRewardsHeadline {
            get {
                return ResourceManager.GetString("settingsRewardsHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewards.
        /// </summary>
        public static string settingsRewardsInfoLink {
            get {
                return ResourceManager.GetString("settingsRewardsInfoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By enabling this feature you are agree to have your username displayed on the {0} page.
        /// </summary>
        public static string settingsRewardsInfoText {
            get {
                return ResourceManager.GetString("settingsRewardsInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string settingsSaveButton {
            get {
                return ResourceManager.GetString("settingsSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Theme.
        /// </summary>
        public static string settingsSiteThemeLabel {
            get {
                return ResourceManager.GetString("settingsSiteThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip ignore List.
        /// </summary>
        public static string settingsTipIgnoreHeadline {
            get {
                return ResourceManager.GetString("settingsTipIgnoreHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User to un/ignore.
        /// </summary>
        public static string settingsTipIgnoreLabel {
            get {
                return ResourceManager.GetString("settingsTipIgnoreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        public static string verificationIdentificationPhoto2ExampleLabel {
            get {
                return ResourceManager.GetString("verificationIdentificationPhoto2ExampleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo holding identification.
        /// </summary>
        public static string verificationIdentificationPhoto2Label {
            get {
                return ResourceManager.GetString("verificationIdentificationPhoto2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        public static string verificationIdentificationPhotoExampleLabel {
            get {
                return ResourceManager.GetString("verificationIdentificationPhotoExampleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo of Identification.
        /// </summary>
        public static string verificationIdentificationPhotoLabel {
            get {
                return ResourceManager.GetString("verificationIdentificationPhotoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification image must be PNG, BMP, JPG or JPEG format..
        /// </summary>
        public static string verificationImageFormatError {
            get {
                return ResourceManager.GetString("verificationImageFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification image is required..
        /// </summary>
        public static string verificationImageRequiredError {
            get {
                return ResourceManager.GetString("verificationImageRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Level1.
        /// </summary>
        public static string verificationLevelOneHeadline {
            get {
                return ResourceManager.GetString("verificationLevelOneHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users verified by email have a daily withdrawal limit of ${0} NZD.
        /// </summary>
        public static string verificationLevelOneInfoText {
            get {
                return ResourceManager.GetString("verificationLevelOneInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Level3.
        /// </summary>
        public static string verificationLevelThreeHeadline {
            get {
                return ResourceManager.GetString("verificationLevelThreeHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users who need a greater daily withdrawal limit will need to contact the {0} team to request Verification Level3, this level of account is required for:.
        /// </summary>
        public static string verificationLevelThreeInfoText {
            get {
                return ResourceManager.GetString("verificationLevelThreeInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Accounts with Verification Level 2 requiring a higher daily limit.
        /// </summary>
        public static string verificationLevelThreeReason1Text {
            get {
                return ResourceManager.GetString("verificationLevelThreeReason1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Businesses and Corporations.
        /// </summary>
        public static string verificationLevelThreeReason2Text {
            get {
                return ResourceManager.GetString("verificationLevelThreeReason2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Level2.
        /// </summary>
        public static string verificationLevelTwoHeadline {
            get {
                return ResourceManager.GetString("verificationLevelTwoHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users that have provided evidence of their identification have daily limit of ${0} NZD.
        /// </summary>
        public static string verificationLevelTwoInfoText {
            get {
                return ResourceManager.GetString("verificationLevelTwoInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification.
        /// </summary>
        public static string verificationPageTitle {
            get {
                return ResourceManager.GetString("verificationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending request....
        /// </summary>
        public static string verificationSendingMessage {
            get {
                return ResourceManager.GetString("verificationSendingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string verificationStatusCompleteLabel {
            get {
                return ResourceManager.GetString("verificationStatusCompleteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete.
        /// </summary>
        public static string verificationStatusIncompleteLabel {
            get {
                return ResourceManager.GetString("verificationStatusIncompleteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string verificationStatusPendingLabel {
            get {
                return ResourceManager.GetString("verificationStatusPendingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification has been submitted to Cryptopia Ltd.
        /// </summary>
        public static string verificationSubmitedInfoText {
            get {
                return ResourceManager.GetString("verificationSubmitedInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you need to update any of the submitted details, please contact {0}..
        /// </summary>
        public static string verificationSupportLink {
            get {
                return ResourceManager.GetString("verificationSupportLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions.
        /// </summary>
        public static string verificationTermsLabel {
            get {
                return ResourceManager.GetString("verificationTermsLabel", resourceCulture);
            }
        }
    }
}
